.github/workflows/maven.yml
#1 - maven build workflow for [GitHub actions](https://github.com/features/actions)
=> Maven build github action

index.html
#1 - using `artipie/artipie` instead of `yegor256/artipie`
=> Fixed repo path

.rultor.yml
=> Removed readers

pom.xml, src/main/java/com/artipie/Pie.java, src/main/java/com/artipie/RepoConfig.java
#26 - resolve files adapter from config
=> Resolve files adapter from config

README.md, pom.xml, src/main/java/com/artipie/VertxMain.java
#12 - implemented main class to start Artipie in Vertx server from https://github.com/artipie/vertx-server
=> Vertx server for artipie

pom.xml, src/main/java/com/artipie/Pie.java, src/main/java/com/artipie/RepoConfig.java, src/main/resources/log4j.properties
#33 - fixed Artipie server and config parsing
=> Fixed artipie config parsing

CODE_STYLE.md
Part of issue #36 
Added topic on reasons in assertions in unit tests.
=> #36 - Code style doc update regarding reasons in unit tests

pom.xml, src/main/java/com/artipie/VertxMain.java
=> Use command line options instead of props

CODE_STYLE.md, Dockerfile
=> Add dockerfile

pom.xml, src/main/java/com/artipie/Pie.java
#47 - integrated NPM adapter as Artipie module
=> Added NPM adapter

pom.xml, src/main/java/com/artipie/Pie.java, src/main/java/com/artipie/RepoConfig.java, src/main/java/com/artipie/YamlSettings.java
Part of issue #38 
Upgraded asto lib to 0.16, that is first release containing S3Storage
=> #38 - Upgraded ASTO to 0.16

pom.xml, src/main/java/com/artipie/Pie.java
=> Add gem adapter to artipie

src/main/java/com/artipie/YamlSettings.java, src/test/java/com/artipie/YamlSettingsTest.java
Part of issue #38 
Added support for S3 storage type to 'YamlSettings'
=> #38 - S3 storage support in YAML settings

.github/workflows/docker-build.yml, Dockerfile
Docker build actions has been created. Such issues as #49, would not occur anymore.
This pull request is blocked by #50.
Closes #49
=> Docker build actions

pom.xml, src/main/java/com/artipie/Pie.java, src/main/java/com/artipie/RepoConfig.java
Part of #58 
Added PHP Composer repository support to Artipie core
=> #58 - Added PHP Composer repository support

src/main/java/com/artipie/RepoConfig.java, src/main/java/com/artipie/YamlSettings.java, src/main/java/com/artipie/YamlStorageSettings.java, src/test/java/com/artipie/YamlStorageSettingsTest.java
Closes #58 
Extracted YamlStorageSettings from YamlSettings and used it in RepoConfig
=> #58 - S3 support in RepoConfig

README.md
Made several corrections in readme.
=> Cosmetic corrections in readme

README.md
Related to #69. I've added description about repository permissions configuration in readme.
=> Added repo permission conf description

README.md, pom.xml, src/main/java/com/artipie/Pie.java
#76 - added rpm repository support
=> RPM repository

pom.xml, src/main/java/com/artipie/Pie.java, src/main/java/com/artipie/RepoConfig.java, src/main/java/com/artipie/VertxMain.java, src/main/java/com/artipie/YamlSettings.java, src/main/java/com/artipie/YamlStorageSettings.java, src/test/java/com/artipie/YamlSettingsTest.java, src/test/java/com/artipie/YamlStorageSettingsTest.java
This pull request also includes ppom and asto dependency update
Closes #81
=> fix Vert.x warning

pom.xml, src/main/java/com/artipie/Pie.java
=> Added maven repo

src/main/java/com/artipie/YamlStorageSettings.java, src/test/java/com/artipie/YamlStorageSettingsTest.java
=> #99 - Optional region & endpoint params in S3 storage config

.github/workflows/docker-release.yml, .github/workflows/maven.yml
add java 13 to maven build target
=> 97 java version

.github/workflows/docker-release.yml
cicd add latest to docker registry #91
=> cicd add latest to docker registry #91

.github/workflows/docker-release.yml
parameterization of credential for docker registries
=> parameterization of credential for docker registries

src/main/java/com/artipie/Pie.java, src/main/java/com/artipie/SliceFromConfig.java
Resolving issue #90 
Added SliceFromConfig class
Added puzzle to test the new class
=> #90 - SliceFromConfig class

pom.xml, src/main/java/com/artipie/SliceFromConfig.java
For #98 I've added go-adapter as a dependency and corresponding slice
=> For #98 added go adapter

pom.xml, src/main/java/com/artipie/Pie.java, src/main/java/com/artipie/SliceFromConfig.java
This pull request brings `gem push` and `gem install` support to Artipie
=> Bump gem adapter version

pom.xml, src/main/java/com/artipie/RepoConfig.java, src/main/java/com/artipie/SliceFromConfig.java
Closes #102 
Added NuGet repository support
=> #102 - Added NuGet repository support

pom.xml, src/main/java/com/artipie/SliceFromConfig.java, src/test/java/com/artipie/SliceFromConfigTest.java
For #109 added test for `SliceFromConfig` and updated artipie-http version.
=> For #109 test for SliceFromConfig

src/main/java/com/artipie/Pie.java
#74 - added check if config exist and return 404 HTTP code if does not
=> Return 404 if repo config doesnt exist

pom.xml, src/main/java/com/artipie/SliceFromConfig.java
Added pypi-adapter to main artipie project. Closes 
https://github.com/artipie/artipie/issues/116 ticket.
=> #116 - add pypi-adapter support to main project

README.md
Constant tags are bad because they always should be updated
=> Recommend to use the latest version

pom.xml
#138 - updated asto with S3 storage fix
=> Updated asto

src/main/java/com/artipie/VertxMain.java
=> Artipie start log

README.md
Closes #124 
Added short and simple example fro NuGet repository configuration and usage to README.md
=> #124 - Added simple NuGet repository example to README.md

README.md
=> #123 - Added simple PHP Composer repository example to README.md

README.md
=> Add a gem example

README.md, pom.xml, src/main/java/com/artipie/RepoConfig.java, src/main/java/com/artipie/SliceFromConfig.java, src/main/java/com/artipie/YamlStorageSettings.java, src/main/java/com/artipie/auth/AuthFromEnv.java, src/main/java/com/artipie/auth/package-info.java, src/test/java/com/artipie/SliceFromConfigTest.java
#148 - fixed http module authentication and added implementation via env variables
=> Authentication via env variables

src/main/java/com/artipie/VertxMain.java
=> let main thread exit after initialization

README.md
Added repo path to yaml example for go.
=> Added repo path to yaml example for go

pom.xml, src/main/java/com/artipie/YamlAuth.java, src/test/java/com/artipie/YamlAuthTest.java
Started authentication from yaml implementation for #146 by creating test. Also upgraded http module dependency and added todo to continue.
=> Authentication from yaml implementation #146

README.md, src/main/java/com/artipie/YamlAuth.java
=> Document yaml auth for #146

src/main/java/com/artipie/Settings.java, src/main/java/com/artipie/YamlSettings.java, src/main/java/com/artipie/auth/AuthFromYaml.java, src/test/java/com/artipie/auth/AuthFromYamlTest.java, src/test/java/com/artipie/auth/package-info.java
For #146 implemented AuthFromYaml and added todo to continue.
=> Implemented AuthFromYaml for #146

pom.xml
=> update npm adapter

pom.xml, src/main/java/com/artipie/Pie.java, src/main/java/com/artipie/RepoConfig.java, src/main/java/com/artipie/SliceFromConfig.java, src/main/java/com/artipie/VertxMain.java, src/main/java/com/artipie/YamlSettings.java, src/main/java/com/artipie/YamlStorageSettings.java, src/test/java/com/artipie/RepoConfigTest.java, src/test/java/com/artipie/SliceFromConfigTest.java, src/test/java/com/artipie/YamlSettingsTest.java, src/test/java/com/artipie/YamlStorageSettingsTest.java
#159 - updated asto to `0.20.2`, using repo names as storage prefixes.
=> Using storage prefixes

src/main/java/com/artipie/Pie.java, src/main/java/com/artipie/Settings.java, src/main/java/com/artipie/SliceFromConfig.java, src/main/java/com/artipie/YamlSettings.java, src/test/java/com/artipie/YamlSettingsTest.java
Implemented `com.artipie.YamlSettings#auth` method to obtain configured Authentication.
=> Obtain auth for #146

README.md, src/main/java/com/artipie/SliceFromConfig.java
=> enable npm auth and fix path issue

src/main/java/com/artipie/Pie.java, src/main/java/com/artipie/Settings.java, src/test/java/com/artipie/PieTest.java
=> Test Pie retuns 404 for missing repository

pom.xml, src/main/java/com/artipie/SliceFromConfig.java
=> #192 - Auth support for NuGet

README.md, pom.xml, src/main/java/com/artipie/SliceFromConfig.java
=> #172 - Docker support added

README.md, pom.xml, src/main/java/com/artipie/SliceFromConfig.java
=> Add helm adapter

.gitignore, src/main/resources/dashboard/base.hbs, src/main/resources/dashboard/repo.hbs, src/main/resources/dashboard/sorry.hbs, src/main/resources/dashboard/user.hbs
See #210 
I tried to improve the UI of the dashboard
=> #210 - UI redesign

src/main/java/com/artipie/Settings.java, src/main/java/com/artipie/YamlSettings.java, src/main/java/com/artipie/api/ApiChangeUserPassword.java, src/main/java/com/artipie/api/ArtipieApi.java, src/main/java/com/artipie/api/AuthApi.java, src/main/resources/dashboard/user.hbs
#218 - added reset password form for user page
=> Reset password form

src/main/resources/dashboard/base.hbs, src/main/resources/dashboard/repo.hbs
See #219: I made some small improvements to the UI
=> #219 - UI improved

pom.xml, src/main/java/com/artipie/SliceFromConfig.java
Updated rpm version added auth.
=> Added auth for rpm

src/main/java/com/artipie/SliceFromConfig.java
=> HTTP proxy config

src/main/resources/dashboard/base.hbs, src/main/resources/dashboard/repo.hbs, src/main/resources/dashboard/user.hbs
See #224: I made some small improvements
=> #224 - UI tweaks

README.md, pom.xml, src/main/java/com/artipie/SliceFromConfig.java
Closes #237 
Added support for `docker-proxy` repository type
=> #237 - Added docker-proxy repository support

src/main/java/com/artipie/metrics/Counter.java, src/main/java/com/artipie/metrics/Gauge.java, src/main/java/com/artipie/metrics/Metrics.java, src/main/java/com/artipie/metrics/package-info.java
Part of #231 
Added interfaces for metrics collecting without implementations
=> #231 - Added metrics interfaces

src/main/java/com/artipie/metrics/memory/InMemoryCounter.java, src/main/java/com/artipie/metrics/memory/package-info.java, src/test/java/com/artipie/metrics/memory/InMemoryCounterTest.java, src/test/java/com/artipie/metrics/memory/package-info.java
Part of #231 
Added `InMemoryCounter` implementation
=> #231 - Added InMemoryCounter

.github/workflows/reports.yml, pom.xml
#249 - bump `asto` 0.23.1 to fix FS atomic save.
=> Atomic save for file storage.

src/main/java/com/artipie/Pie.java, src/main/java/com/artipie/Settings.java, src/main/java/com/artipie/SliceFromConfig.java, src/main/java/com/artipie/YamlSettings.java, src/main/java/com/artipie/repo/FlatLayout.java, src/main/java/com/artipie/repo/OrgLayout.java, src/main/java/com/artipie/repo/PathPattern.java
#233 - group repositories implementation
=> Group repositories implementation

pom.xml
Updated rpm version to make `sha256` default naming policy in config from yaml.
=> Updated rpm version

src/main/java/com/artipie/Pie.java
=> Remove \r\n in request line logging

src/main/java/com/artipie/metrics/PrefixedMetrics.java, src/test/java/com/artipie/metrics/PrefixedMetricsTest.java, src/test/java/com/artipie/metrics/package-info.java
Part of #231 
Added `PrefixedMetrics` class for adding a prefix to all names in origin `Metrics`
=> #231 - Added PrefixedMetrics

README.md, pom.xml, src/main/java/com/artipie/RepoConfig.java, src/main/java/com/artipie/SliceFromConfig.java
Closes #250 
Added support for caching to `docker-proxy` repo type
=> #250 - Support for caching Docker proxy

src/main/java/com/artipie/ResponseMetricsSlice.java, src/test/java/com/artipie/ResponseMetricsSliceTest.java
Part of #231 
Collecting metrics for unauthorized responses in ResponseMetricsSlice
=> #231 - Reporting unauthorized responses in ResponseMetricsSlice

README.md, src/main/java/com/artipie/ResponseMetricsSlice.java, src/main/java/com/artipie/VertxMain.java, src/test/java/com/artipie/ResponseMetricsSliceTest.java
Closes #231 
Creating metrics from settings and enabling publishing on start of application
=> #231 - Enabled metrics collecting and publishing to log

pom.xml
=> Updated pypi

src/main/java/com/artipie/VertxMain.java
Part of #304 
`metrics` are not required in settings, fixed crash on startup when `metrics` are not specified
=> #304 - Fixed crash on start when metrics not specified

README.md, example/artipie.yaml, src/main/java/com/artipie/VertxMain.java, src/main/java/com/artipie/metrics/MetricsFromConfig.java, src/main/java/com/artipie/metrics/memory/MetricsLogPublisher.java, src/test/java/com/artipie/metrics/MetricsFromConfigTest.java
For #305 I've extracted `MetricsFromConfig` class, added unit test for it and remove empty metrics printing.
=> #305 - log metrics interval

README.md
For #176: Added basic auth information on readme
=> For #176: Added basic auth information to readme

examples/docker/README.md, pom.xml, src/main/java/com/artipie/docker/DockerProxy.java
Closes #332 
Using storage configured in proxy for write operations
=> #332 - Docker virtual repository support

examples/binary/run.sh, examples/helm/run.sh, examples/maven/configs/my-maven.yaml, examples/maven/run.sh, examples/maven/sample-consumer/pom.xml, examples/maven/sample-for-deployment/pom.xml
This repository provides a proof that maven repository actually works.
Related to #154.
=> Maven proof

pom.xml, src/main/java/com/artipie/SliceFromConfig.java
Updated pypi to 0.5 and used trim slice for Python slice.
=> Updated pypi to 0.5

pom.xml
=> Add slf4j api dependency

pom.xml, src/main/java/com/artipie/SliceFromConfig.java
Trim request paths for gem adapter and update adapter version. 
Related to #54
Waiting for https://github.com/artipie/gem-adapter/pull/48 to merge and release
=> Trim path for gem adapter

examples/docker/README.md, src/main/java/com/artipie/RepoConfig.java, src/main/java/com/artipie/docker/DockerProxy.java
Closes #333 
Added support for multiple remotes for docker proxy repository
=> #333 - Multi remote docker proxy support

pom.xml
This version will make gem proof to pass:
Related to #154 and #54
=> Update gem adapter version

pom.xml, src/test/java/com/artipie/http/GroupRepositoryITCase.java
#370 - reproduced HTTP proxy issue with integration test, fixed in http module, and update http version.
=> Reproduced with integration test and fixed in http module

examples/docker/configs/my-docker.yaml, examples/docker/run.sh
A proof that docker repo works. 
Related to #154.
=> Docker proof

pom.xml, src/main/java/com/artipie/SliceFromConfig.java
Closes #383 
Upgraded NuGet to 0.3 with updated ASTO and HTTP dependencies and removed base path support
=> #383 - Upgraded NuGet to 0.3

pom.xml
Updated pypi version to close #387.
=> #387 - update pypi to 0.5.4

examples/docker/configs/my-docker.yaml
Related to #390, #154 and #393.
=> Fix docker proof broken in #390

src/main/java/com/artipie/docker/DockerProxy.java, src/test/java/com/artipie/docker/DockerProxyTest.java, src/test/java/com/artipie/docker/package-info.java
Closes #338 
Added unit tests for `DockerProxy` with valid and invalid configuration examples
=> #338 - Added unit tests for DockerProxy

src/main/java/com/artipie/YamlPermissions.java, src/test/java/com/artipie/YamlPermissionsTest.java
Closes #399 
Everthing is allowed when no permissions in repo YAML
=> #399 - Everthing is allowed when no permissions in repo YAML

Dockerfile
=> Docker caching layer for maven dependecies

examples/npm/run.sh
Use `artipie/artipie:latest` instead of `artipie-local:latest`
Related to #154
=> Fix npm proof

src/main/java/com/artipie/http/Pie.java, src/main/java/com/artipie/http/TimeoutSlice.java, src/test/java/com/artipie/http/TimeoutSliceTest.java
#409 - wrapped `Pie` slices with `TimeoutSlice`
=> Cancel request by timeout

.github/workflows/proof-binary.yaml, .github/workflows/proof-docker.yml, .github/workflows/proof-gem.yml, .github/workflows/proof-helm.yml, .github/workflows/proof-maven.yml, .github/workflows/proof-npm.yml, .github/workflows/proof-pypi.yml
Force some of the reliable proofs to pass on each pull request.
Related to #154
=> Reliable proofs

src/main/java/com/artipie/VertxMain.java, src/main/java/com/artipie/http/TrafficMetricSlice.java, src/test/java/com/artipie/http/TrafficMetricSliceTest.java, src/test/java/com/artipie/metrics/memory/InMemoryMetricsTest.java, src/test/java/com/artipie/metrics/memory/TestMetricsOutput.java
#425 - collected size of requests body publisher and response body publisher and increments traffic metrics.
=> Collected traffic metrics from requests and responses

pom.xml
To close #421 - update pypi adapter to 0.6.
=> #421 - update pypi to 0.6

pom.xml
Closes #427 
Docker upgraded to 4.0.1
=> #427 - Docker upgraded to 4.0.1

.github/workflows/release.yml
Benchmark publication process has been changed in accordance with the latest changes in the benchmarking repository.
Related to #431 
Those changes were tested on my fork repository.
=> Benchmarks publication process changes

.github/workflows/proof-gem.yml
Disabled broken test for gem-adapter
=> Disabled broken gem adapter test

pom.xml
Updated rpm-adapter version to `1.0`.
=> Updated rpm version to 1.0

src/main/java/com/artipie/VertxMain.java
Part of #449 
Refactoring of `VertxMain` to make it possible to start and stop an instance in tests.
=> #449 - VertxMain start and stop extracted

src/main/java/com/artipie/Settings.java, src/main/java/com/artipie/api/ArtipieApi.java, src/main/java/com/artipie/api/artifactory/GetUserSlice.java, src/test/java/com/artipie/api/artifactory/GetUserSliceTest.java
Part of #444 - created test for `GetUserSlice` and added corresponding endpoint to `ArtipieApi`.
=> #444 - GetUserSlice tested and added to ArtipieApi

pom.xml
=> Fix docker and pypi proofs

.github/workflows/proof-gem.yml, pom.xml
=> Enable gem proof

src/main/java/com/artipie/Settings.java, src/main/java/com/artipie/api/ArtipieApi.java, src/main/java/com/artipie/api/artifactory/GetUsersSlice.java, src/main/resources/example/artipie.yaml, src/test/java/com/artipie/api/artifactory/GetUserSliceTest.java, src/test/java/com/artipie/api/artifactory/GetUsersSliceTest.java
For  #444 implemented `GetUsersSlice` to obtain users list with urls.
=> #444 - GetUsersSlice introduced

src/main/java/com/artipie/Credentials.java, src/main/java/com/artipie/api/artifactory/AddUpdateUserSlice.java, src/main/java/com/artipie/api/artifactory/DeleteUserSlice.java, src/test/java/com/artipie/CredentialsFromStorageYamlTest.java
Part of #444 
I've fully implemented `Credentials.FromStorageYaml` and added puzzles for `DeleteUserSlice` and for `AddUpdateUserSlice`.
=> #444 - Credentials.FromStorageYaml fully implemented

pom.xml, src/main/java/com/artipie/metrics/MetricSlice.java, src/test/java/com/artipie/metrics/MetricSliceTest.java
Closes #447 
`MetricSliceTest` was added.
=> #447 - Add MetricSliceTest

src/test/java/com/artipie/docker/Image.java
Part of #499
Added `Image` interface to represent Docker image in tests.
=> #499 - Docker Image class added

src/main/java/com/artipie/api/ArtipieApi.java, src/main/java/com/artipie/api/artifactory/AddUpdateUserSlice.java, src/test/java/com/artipie/api/artifactory/AddUpdateUserSliceTest.java
Closes #479 
Added `AddUpdateUserSlice` and tested this class.
=> #479 - AddUpdateUserSlice

src/test/java/com/artipie/ArtipieServer.java, src/test/java/com/artipie/docker/DockerLocalIT.java
Part of #489 
Added pull and push tests for Docker local repository type.
=> #499 - Docker local push and pull integration tests added

pom.xml, src/main/java/com/artipie/RepoPermissions.java, src/main/java/com/artipie/api/artifactory/AddUpdatePermissionSlice.java, src/main/java/com/artipie/api/artifactory/DeletePermissionSlice.java, src/main/java/com/artipie/api/artifactory/GetPermissionSlice.java, src/main/java/com/artipie/api/artifactory/GetPermissionsSlice.java, src/test/java/com/artipie/RepoPermissionsFromSettingsTest.java
Part of #444 
Created skeleton to implement permissions API.
=> #444 - permissions API skeleton

src/main/java/com/artipie/RepoPermissions.java, src/test/java/com/artipie/RepoPermissionsFromSettingsTest.java
Part of #495 
Implemented `RepoPermissions.FromSettings.permissions()` method to return repository users and permissions
=> #495 - implemented RepoPermissions.FromSettings.permissions() method

src/main/java/com/artipie/api/ArtipieApi.java, src/main/java/com/artipie/api/artifactory/GetPermissionsSlice.java, src/test/java/com/artipie/api/artifactory/GetPermissionsSliceTest.java
Closes #496
Add `GetPermissionsSlice` and tests.
=> #496 - Add GetPermissionsSlice and tests

pom.xml
=> Fix jcabi-xml version

src/main/java/com/artipie/api/artifactory/AddUpdateUserSlice.java, src/main/java/com/artipie/api/artifactory/DeleteUserSlice.java, src/main/java/com/artipie/api/artifactory/GetUserSlice.java, src/main/java/com/artipie/api/artifactory/UserFromRqLine.java, src/test/java/com/artipie/api/artifactory/UserFromRqLineTest.java
Closes #484 
Add class `UserFromRqLine` for receiving username from the request line.
=> #484 - Add UserFromRqLine

src/main/java/com/artipie/api/ArtipieApi.java, src/main/java/com/artipie/api/artifactory/GetPermissionSlice.java, src/test/java/com/artipie/api/artifactory/GetPermissionSliceTest.java
Implemented `GetPermissionSlice` for #495
=> #495 - GetPermissionSlice implemented

src/main/java/com/artipie/SliceFromConfig.java, src/test/java/com/artipie/docker/DockerProxyIT.java
Part of #499 
Docker proxy integration tests added
=> #499 - Docker proxy integration tests

src/main/java/com/artipie/api/ArtipieApi.java, src/main/java/com/artipie/api/artifactory/DeletePermissionSlice.java, src/test/java/com/artipie/api/artifactory/DeletePermissionSliceTest.java
For #497 I've implemented `DeletePermissionSlice` and added it to `ArtipieApi`.
=> #497 - DeletePermissionSlice implemented

src/main/java/com/artipie/api/ArtipieApi.java, src/main/java/com/artipie/api/artifactory/AddUpdatePermissionSlice.java, src/test/java/com/artipie/api/artifactory/AddUpdatePermissionSliceTest.java
For #494 I've implemented `AddUpdatePermissionSlice`.
=> #494 - AddUpdatePermissionSlice implemented

pom.xml
=> Updated RPM to 1.1

.github/workflows/proof-nuget.yml, examples/nuget/configs/my-nuget.yaml, examples/nuget/run.ps1, examples/nuget/sample-consumer/SampleConsumer.nuspec, examples/nuget/sample-for-deployment/SampleForDeployment.nuspec, examples/nuget/sample-for-deployment/data.txt, pom.xml
Fixes #517 NuGet install 
Related to #154
=> Nuget proof

src/test/java/com/artipie/ArtipieServer.java
Part of #499 
Added predefined users to `ArtipieServer`, so they can be used to check auth later
=> #499 - Added predefined users to ArtipieServer

examples/binary/README.md, examples/binary/configs/repo.yaml, examples/docker/configs/my-docker.yaml, examples/gem/configs/my-gem.yaml, examples/go/README.md, examples/helm/README.md, examples/helm/configs/example_helm_repo.yaml, examples/maven/README.md, examples/maven/configs/my-maven.yaml, examples/npm/configs/npm_repo.yaml, examples/php/configs/bin.yaml, examples/php/configs/my-php.yaml, examples/pypi/README.md, examples/pypi/configs/my-pypi.yaml, examples/rpm/configs/my-rpm.yaml
Closes #498 
Remove permissions from examples config `.yml` and `Readme`.
=> #498 - Remove permissions

src/main/java/com/artipie/api/ArtipieApi.java, src/main/java/com/artipie/api/artifactory/AddUpdatePermissionSlice.java, src/main/java/com/artipie/api/artifactory/AddUpdateUserSlice.java, src/main/java/com/artipie/api/artifactory/DeletePermissionSlice.java, src/main/java/com/artipie/api/artifactory/DeleteUserSlice.java, src/main/java/com/artipie/api/artifactory/FromRqLine.java, src/main/java/com/artipie/api/artifactory/GetPermissionSlice.java, src/main/java/com/artipie/api/artifactory/GetUserSlice.java, src/test/java/com/artipie/api/artifactory/FromRqLineTest.java
Closes #515 
Replace `UserFromRqLine ` with `FromRqLine`. `FromRqLine` has regex patterns for receiving username and repo from request line.
=> #515 - Add FromRqLine for regex patterns

examples/docker/configs/_credentials.yaml, examples/docker/configs/my-docker.yaml, examples/docker/run.sh, pom.xml, src/main/java/com/artipie/http/DockerRoutingSlice.java, src/main/java/com/artipie/http/Pie.java, src/test/java/com/artipie/docker/DockerLocalAuthIT.java, src/test/java/com/artipie/docker/DockerLocalIT.java, src/test/java/com/artipie/docker/DockerProxyIT.java, src/test/java/com/artipie/docker/DockerProxyTest.java, src/test/java/com/artipie/docker/junit/DockerClient.java, src/test/java/com/artipie/http/DockerRoutingSliceTest.java
Closes #521 
Proper response from `/v2/` endpoint
=> #521 - Auth fix for Docker repositories

src/test/java/com/artipie/docker/DockerLocalAuthIT.java, src/test/java/com/artipie/docker/junit/DockerClient.java
Part of #524 
Testing denied write and denied read access to Docker repository
=> #524 - Testing denied write and denied read access to Docker repository

src/main/java/com/artipie/Credentials.java, src/main/java/com/artipie/api/ApiChangeUserPassword.java, src/main/java/com/artipie/api/artifactory/AddUpdateUserSlice.java, src/test/java/com/artipie/CredentialsFromStorageYamlTest.java, src/test/java/com/artipie/api/ApiChangeUserPasswordTest.java, src/test/java/com/artipie/api/artifactory/AddUpdateUserSliceTest.java, src/test/java/com/artipie/api/package-info.java
Part of #507 - refactored `ApiChangeUserPassword` to use `Credentials` interface and its implementations to change user password.
=> #507 - refactored ApiChangeUserPassword.java

src/test/java/com/artipie/docker/DockerLocalAuthIT.java
Closes #524 
Testing not authenticated access to Docker repository
=> #524 - Testing not authenticated access to Docker repository

benchmarks/index.html
=> Ubuntu single upload visualization

examples/gem/run.sh, pom.xml
Migrate to gem-adapter version 0.4 and fix gem proof.
Related to #154.
=> Migrate to gem 0.4

ARTIFACTORY_API_SUPPORT.md
For #555 I've documented permissions API.
=> #555 - permissions API documented

examples/binary/README.md
=> Binary example documentation imrpvements

examples/docker/README.md
=> Rework docker docs structure

README.md
Remove Artifactory from README.
We shall change the name of the link in the future  from /ARTIFACTORY_API_SUPPORT.md to something Artipie_API.md
=> Create the section for Artifact APIs Update README.md 

src/main/java/com/artipie/api/artifactory/KeyList.java, src/test/java/com/artipie/api/artifactory/KeyListTest.java
Part of #548 
Fixed parent detection in KeyList
=> #548 - Fixed parent detection in KeyList

src/main/java/com/artipie/Credentials.java, src/main/java/com/artipie/api/ApiChangeUserPassword.java, src/main/java/com/artipie/api/artifactory/AddUpdateUserSlice.java, src/main/java/com/artipie/api/artifactory/DeleteUserSlice.java, src/main/java/com/artipie/api/artifactory/GetUserSlice.java, src/main/java/com/artipie/api/artifactory/GetUsersSlice.java, src/test/java/com/artipie/CredentialsFromEnvTest.java, src/test/java/com/artipie/CredentialsFromStorageYamlTest.java, src/test/java/com/artipie/api/artifactory/AddUpdateUserSliceTest.java
Part of #569 
I've added `Credentials.User` class with username and email, changed methods of `Credentials` signature, implementations and usages. 
Next part would be to properly correct and extend tests.
=> #569 - created Credentials.User

pom.xml, src/test/java/com/artipie/IsJson.java, src/test/java/com/artipie/api/artifactory/GetStorageSliceTest.java
Part of #548 
Added tests for `GetStorageSlice`
=> #548 - Tests for GetStorageSlice

Artipie_REST_API
Our document shall focus on Artipies. I only change the top section and will review the rest later.
=> Update and rename ARTIFACTORY_API_SUPPORT.md to Artipie_REST_API

REST_API.md, src/main/java/com/artipie/Credentials.java, src/test/java/com/artipie/CredentialsFromEnvTest.java, src/test/java/com/artipie/CredentialsFromStorageYamlTest.java, src/test/java/com/artipie/api/artifactory/AddUpdateUserSliceTest.java
Closes #569 
Extended and fixed tests for user email
=> #569 - tests for user emails

src/main/java/com/artipie/Settings.java, src/main/java/com/artipie/api/artifactory/GetStorageSlice.java, src/test/java/com/artipie/api/artifactory/GetStorageSliceRequestTest.java
Part of #545 
Request parsing for `GetStorageSlice`
=> #545 - Request parsing for GetStorageSlice

REST_API.md, src/main/java/com/artipie/api/ArtipieApi.java, src/main/java/com/artipie/api/artifactory/GetStorageSlice.java, src/test/java/com/artipie/api/artifactory/GetStorageSliceTest.java
Closes #545 
`GetStorageSlice` implemented, routing added and docs updated
=> #545 - GetStorageSlice implemented

examples/go/README.md
=> GOPROXY docs improved

examples/gem/README.md
Gem docs have been updated.
Related to #361
=> Gem docs updated

src/main/java/com/artipie/RepoPermissions.java, src/main/java/com/artipie/api/artifactory/AddUpdatePermissionSlice.java, src/test/java/com/artipie/RepoPermissionsFromSettingsTest.java, src/test/java/com/artipie/RepoPerms.java
Part of #571 
Added included path patterns support to `RepoPermissions#update`
=> #571 - Added included path patterns support to RepoPermissions.update

src/main/java/com/artipie/api/artifactory/AddUpdatePermissionSlice.java, src/test/java/com/artipie/api/artifactory/AddUpdatePermissionSliceTest.java
Part of #571 
Support for `"include-patterns"` in `AddUpdatePermissionSlice`
=> #571 - Support for include-patterns in AddUpdatePermissionSlice

src/main/java/com/artipie/RepoPermissions.java, src/main/java/com/artipie/api/artifactory/GetPermissionSlice.java, src/test/java/com/artipie/RepoPermissionsFromSettingsTest.java, src/test/java/com/artipie/api/artifactory/GetPermissionSliceTest.java
Part of #571 
Reading `include-patterns` in `GetPermissionSlice`
=> #571 - Reading include patterns support in GetPermissionSlice

src/main/java/com/artipie/RepoPermissions.java, src/main/java/com/artipie/api/artifactory/AddUpdatePermissionSlice.java, src/main/java/com/artipie/api/artifactory/GetPermissionSlice.java, src/test/java/com/artipie/RepoPermissionsFromSettingsTest.java, src/test/java/com/artipie/RepoPermissionsPathPatternTest.java
Part of #571 
`PathPattern` introduced with validation
=> #571 - PathPattern introduced

pom.xml, src/main/java/com/artipie/SliceFromConfig.java
Updated go-adapter to close #601
=> #601 - updated go-adapter

src/main/java/com/artipie/api/artifactory/AddUpdatePermissionSlice.java, src/test/java/com/artipie/api/artifactory/AddUpdatePermissionSliceTest.java
Part of #571 
Validating path patterns on update
=> #571 - Validating path patterns on update

REST_API.md, src/main/java/com/artipie/api/artifactory/GetPermissionSlice.java, src/test/java/com/artipie/api/artifactory/GetPermissionSliceTest.java
Part of #571 
Added docs for path patterns support & fixed GET endpoint
=> #571 - Added docs for path patterns support & fixed GET endpoint

src/main/java/com/artipie/api/artifactory/GetUserSlice.java, src/test/java/com/artipie/api/artifactory/GetUserSliceTest.java
Part of #572 
Returning groups in `GetUserSlice`
=> #572 - return groups in GetUserSlice

src/main/java/com/artipie/Users.java, src/main/java/com/artipie/api/artifactory/AddUpdateUserSlice.java, src/test/java/com/artipie/UsersFromStorageYamlTest.java, src/test/java/com/artipie/api/artifactory/AddUpdateUserSliceTest.java
Part of #572 
Read user groups from request json in `AddUpdateUserSlice`
=> #572 - read and save groups in AddUpdateUserSlice

src/test/java/com/artipie/maven/MavenProxyIT.java
Part of #535 
Add `MavenProxyIT`. Artifact are downloading from `maven central`.
=> #535 - Add mavenProxyIT

src/main/java/com/artipie/auth/AuthFromYaml.java
Closes #616 
Simplify `user()` method and get rid of nested if expressions. Also get rid of `check(String, String)` method and use `check()` with three params instead.
=> #616 - Simplify user() method

src/main/java/com/artipie/SliceFromConfig.java, src/main/java/com/artipie/VertxMain.java, src/main/java/com/artipie/docker/DockerProxy.java, src/main/java/com/artipie/http/ArtipieRepositories.java, src/main/java/com/artipie/http/Repositories.java, src/main/java/com/artipie/http/SliceByPath.java, src/test/java/com/artipie/docker/DockerOnPortIT.java, src/test/java/com/artipie/docker/DockerProxyTest.java
Closes #570 
No repo name prefix in path required when accessing repository on it's own port
=> #570 - No repo name prefix on repository ports

pom.xml, src/main/java/com/artipie/MeasuredStorage.java, src/test/java/com/artipie/http/HealthSliceTest.java
=> Bump asto version

src/test/java/com/artipie/FilesRepoITCase.java, src/test/resources/file-repo/curl.txt
Part of #603 
Add IT case for files repository. Verify `PUT` and `GET` with authentication disabled.
=> #603 - Check PUT and GET with auth disabled

src/main/java/com/artipie/MeasuredStorage.java
Closes #637
Configurable log level in `MeasuredStorage`, finest by default
=> #637 - Configurable log level in MeasuredStorage, finest by default

src/test/java/com/artipie/ArtipieServer.java, src/test/java/com/artipie/FilesRepoITCase.java
Closes #603 
Verify `curl` `PUT` and `GET` with authentication enabled.
=> #603 - Verify curl request with authentication 

README.md, examples/docker/README.md
Part of #570 
Added documentation for repo on own port feature
=> #570 - Added documentation for repo on own port feature

REST_API.md, src/main/java/com/artipie/api/artifactory/GetPermissionSlice.java, src/test/java/com/artipie/api/artifactory/GetPermissionSliceTest.java
Part of #573 
Added groups to `GetPermissionSlice` and updated API doc.
=> #573 - add groups to GetPermissionSlice

pom.xml, src/main/java/com/artipie/SliceFromConfig.java, src/test/java/com/artipie/maven/MavenProxyIT.java
Closes #628 
Upgrade maven to `0.6`, enable `mavenProxyIT`.
=> #628 - Enable MavenProxyIT

README.md
Closes #647 
I've [documented](https://github.com/olenagerasimova/artipie/tree/647-storage-conf) storage configuration.
=> #647 - document storage conf

.github/workflows/release.yml
=> Push directly to central.artipie.com and dont fail on error

src/main/java/com/artipie/RepoConfig.java, src/test/java/com/artipie/ArtipieServer.java, src/test/java/com/artipie/RepoConfigYaml.java, src/test/java/com/artipie/maven/MavenITCase.java, src/test/java/com/artipie/maven/MavenProxyIT.java
Part of #660 
Created `RepoConfigYaml` class and used it in Maven ITs.
=> #660 - created RepoConfigYaml

src/test/java/com/artipie/rpm/RpmITCase.java
Part of #604 
Added test for `yum list` and `install`
=> #604 - RPM list and install

src/test/java/com/artipie/FilesRepoITCase.java, src/test/java/com/artipie/RepoConfigYaml.java, src/test/java/com/artipie/RepoPerms.java, src/test/java/com/artipie/docker/DockerLocalAuthIT.java, src/test/java/com/artipie/docker/DockerLocalIT.java
Part of #660 
Added permissions to `RepoConfigYaml` and used it in `FilesRepoITCase` and docker ITs.
=> #660 - files and docker

src/test/java/com/artipie/ArtipieServer.java, src/test/java/com/artipie/RepoConfigYaml.java, src/test/java/com/artipie/maven/MavenProxyAuthIT.java
Part of #668 
Added test for auth for remote in Maven proxy
=> #668 - Added test for auth for remote in Maven proxy

src/test/java/com/artipie/rpm/RpmITCase.java
Closes #604 
Added authorization to `RpmITCase`.
=> #604 - auth added

src/test/java/com/artipie/nuget/NugetITCase.java
Part of #602 
NuGet tests disabled
=> #602 - NuGet tests disabled

src/test/java/com/artipie/pypi/PypiITCase.java
Closes #652 
Verify package installation and  package publishing with authentication in `pypiITCase`
=> #652 - Verify with authentication in pypiIT

examples/maven/README.md
Closes #608 
Updated docs for maven proxy configuration
=> #608 - Updated docs for maven proxy configuration

src/test/java/com/artipie/CredsConfigYaml.java, src/test/java/com/artipie/api/artifactory/AddUpdateUserSliceTest.java, src/test/java/com/artipie/api/artifactory/DeleteUserSliceTest.java, src/test/java/com/artipie/api/artifactory/GetUserSliceTest.java, src/test/java/com/artipie/api/artifactory/GetUsersSliceTest.java
Part of #690 
I've created `CredsConfigYaml` and used it in `api.artifactory` package classes
=> #690 - CredsConfigYaml created

pom.xml, src/main/java/com/artipie/docker/DockerProxy.java, src/main/java/com/artipie/maven/MavenProxy.java, src/main/java/com/artipie/repo/ProxyConfig.java, src/main/java/com/artipie/repo/YamlProxyConfig.java, src/test/java/com/artipie/repo/YamlProxyConfigTest.java
Part of #693 
Using proxy config in Docker proxy
=> #693 - Using proxy config in Docker proxy

src/main/java/com/artipie/RepoConfig.java, src/main/java/com/artipie/docker/DockerProxy.java, src/main/java/com/artipie/maven/MavenProxy.java, src/main/java/com/artipie/repo/ProxyConfig.java, src/main/java/com/artipie/repo/YamlProxyConfig.java, src/test/java/com/artipie/repo/YamlProxyConfigTest.java
Part of #693 
Added `cache` method to `ProxyConfig`
=> #693 - Added cache method to ProxyConfig

src/main/java/com/artipie/maven/MavenProxy.java, src/test/java/com/artipie/maven/MavenMultiProxyIT.java
Closes #694 
Support for multiple remotes in Maven proxy
=> #694 - Support for multiple remotes in Maven proxy

examples/maven/README.md, src/main/java/com/artipie/maven/MavenProxy.java, src/test/java/com/artipie/maven/MavenProxyIT.java
Closes #693 
Updated Maven proxy cache config format
=> #693 - Updated Maven proxy cache config format

src/test/java/com/artipie/ArtipieServer.java, src/test/java/com/artipie/file/FileProxyAuthIT.java, src/test/java/com/artipie/file/FilesRepoITCase.java, src/test/java/com/artipie/file/package-info.java
Part of #692 
Added `FileProxyAuthIT`
=> #692 - Added FileProxyAuthIT

pom.xml, src/main/java/com/artipie/SliceFromConfig.java, src/main/java/com/artipie/file/FileProxy.java, src/main/java/com/artipie/file/package-info.java, src/test/java/com/artipie/file/FileProxyAuthIT.java
Closes #692 
Extracted `FileProxy` and supported auth
=> #692 - Extracted FileProxy and supported auth

pom.xml
Part of #694 
HTTP upgrade for fixed GroupSlice
=> #694 - HTTP upgrade for fixed GroupSlice

src/test/java/com/artipie/auth/AuthAndPermissionsTest.java
Part of #700 
Deprecated classes usage removed in `AuthAndPermissionsTest`
=> #700 - Deprecated classes usage removed in AuthAndPermissionsTest

src/test/java/com/artipie/npm/NpmITCase.java
Part of #605 
Verify that npm publish project without authentication is working.
=> #605 - Verify publish in NpmITCase

src/test/java/com/artipie/pypi/PypiProxyITCase.java
Closes #715 
Created IT for python proxy.
=> #715 - pypi proxy IT

pom.xml, src/main/java/com/artipie/SliceFromConfig.java
Part of #700 
Deprecated classes usage removed in `SliceFromConfig`
=> #700 - Deprecated classes usage removed in SliceFromConfig

src/test/java/com/artipie/npm/NpmITCase.java
Closes #605 
Verify installation and publishing with authentication in `npmITCase`
=> #605 - Verify with authentication in npmIT

examples/binary/README.md
Closes #724 
Added info about files proxy config to readme.
=> #724 - added files proxy config to readme

src/test/java/com/artipie/maven/MavenITCase.java, src/test/java/com/artipie/maven/MavenMultiProxyIT.java, src/test/java/com/artipie/maven/MavenProxyAuthIT.java, src/test/java/com/artipie/maven/MavenProxyIT.java, src/test/java/com/artipie/maven/MavenSettings.java
Part of #722 
Extract `MavenSettings` class and use it
=> #722 - Extract MavenSettings class

src/main/java/com/artipie/api/ApiPermissions.java, src/main/java/com/artipie/api/AuthApi.java, src/test/java/com/artipie/api/ApiPermissionsTest.java
Part of #700 
Extracted `ApiPermissions` from `AuthApi`
=> #700 - Extracted ApiPermissions from AuthApi

src/main/java/com/artipie/api/Cookies.java, src/test/java/com/artipie/api/CookiesTest.java
Part of #700 
Extracted `Cookies` from `AuthApi`
=> #700 - Extracted Cookies from AuthApi

src/main/java/com/artipie/RepoPermissions.java, src/main/java/com/artipie/Settings.java, src/main/java/com/artipie/SliceFromConfig.java, src/main/java/com/artipie/VertxMain.java, src/main/java/com/artipie/api/artifactory/CreateRepoSlice.java, src/main/java/com/artipie/api/artifactory/DeletePermissionSlice.java, src/main/java/com/artipie/api/artifactory/GetPermissionSlice.java, src/main/java/com/artipie/api/artifactory/GetPermissionsSlice.java, src/main/java/com/artipie/api/artifactory/GetStorageSlice.java, src/main/java/com/artipie/api/artifactory/GetUsersSlice.java, src/main/java/com/artipie/http/ArtipieRepositories.java, src/main/java/com/artipie/http/MainSlice.java, src/main/java/com/artipie/http/RtIsDashboard.java, src/main/java/com/artipie/repo/PathPattern.java
Closes #729 
I've removed `IOException` from `Settings`'s methods signature and corrected all usages.
=> #729 - remove `IOException` from `Settings`

src/main/java/com/artipie/api/ApiAuthSlice.java
Closes #700 
Removed deprecated classes usage in `ApiAuthSlice`
=> #700 - Removed deprecated classes usage in ApiAuthSlice

src/main/java/com/artipie/api/ArtipieApi.java, src/main/java/com/artipie/api/artifactory/AddUpdateUserSlice.java, src/main/java/com/artipie/api/artifactory/DeleteUserSlice.java, src/main/java/com/artipie/api/artifactory/GetUserSlice.java, src/main/java/com/artipie/api/artifactory/GetUsersSlice.java, src/test/java/com/artipie/api/artifactory/AddUpdateUserSliceTest.java, src/test/java/com/artipie/api/artifactory/DeleteUserSliceTest.java, src/test/java/com/artipie/api/artifactory/GetUserSliceTest.java, src/test/java/com/artipie/api/artifactory/GetUsersSliceTest.java
Part of #730 
I've changed user API slices do not depend on `Settings`.
=> #730 - user API

src/main/java/com/artipie/api/ApiChangeUserPassword.java, src/main/java/com/artipie/api/ApiRepoCreateSlice.java, src/main/java/com/artipie/api/ApiRepoGetSlice.java, src/main/java/com/artipie/api/ApiRepoListSlice.java, src/main/java/com/artipie/api/ApiRepoUpdateSlice.java, src/main/java/com/artipie/api/ArtipieApi.java, src/test/java/com/artipie/api/ApiChangeUserPasswordTest.java
Part of #730 
Changed Artipie API slices not to use `Settings`.
=> #730 - artipie API slices changed

pom.xml
I've updated asto, maven and python.
=> Updated asto, maven and python

src/main/java/com/artipie/Repositories.java, src/main/java/com/artipie/RepositoriesFromStorage.java, src/main/java/com/artipie/SliceFromConfig.java, src/main/java/com/artipie/api/artifactory/GetStorageSlice.java, src/main/java/com/artipie/http/ArtipieRepositories.java, src/main/java/com/artipie/http/SliceByPath.java
Part of #597 
Unified some code for reading repository config by name
=> #597 - Unified code for reading repository config by name

src/main/java/com/artipie/RepositoriesFromStorage.java, src/main/java/com/artipie/VertxMain.java, src/main/java/com/artipie/api/artifactory/GetStorageSlice.java, src/main/java/com/artipie/http/ArtipieRepositories.java
Closes #597 
All repository config creation code duplication removed
=> #597 - All repository config creation code duplication removed

pom.xml
#680
Failing integration tests should cause GitHub check to fail
=> #680 - Fix for integration tests action

src/main/java/com/artipie/VertxMain.java, src/test/java/com/artipie/docker/DockerProxyIT.java, src/test/java/com/artipie/nuget/NugetITCase.java
=> #597 - Configs reading fixed

pom.xml, src/main/java/com/artipie/SliceFromConfig.java, src/main/java/com/artipie/repo/YamlProxyConfig.java, src/test/java/com/artipie/docker/DockerProxyIT.java, src/test/java/com/artipie/nuget/NugetITCase.java, src/test/java/com/artipie/repo/YamlProxyConfigTest.java
#597
Re-enabled NuGet and Docker proxy integration tests
=> #597 - Re-enabled NuGet and Docker proxy integration tests

pom.xml
Bumped rpm-adapter version to 1.3.2
=> Updated rpm to 1.3.2

src/main/java/com/artipie/SliceFromConfig.java, src/test/java/com/artipie/gem/GemITCase.java
Closes #768
Support authentication for Gem repository. Disable corresponding IT case.
=> #768 - Support authentication for Gem

src/main/java/com/artipie/RepositoriesFromStorage.java, src/test/java/com/artipie/RepoConfigYaml.java, src/test/java/com/artipie/RepositoriesFromStorageTest.java
Part of #597 
Added tests for `RepositoriesFromStorage`
=> #597 - Test RepositoriesFromStorage

src/main/java/com/artipie/Layout.java, src/main/java/com/artipie/Settings.java, src/main/java/com/artipie/SliceFromConfig.java, src/main/java/com/artipie/YamlSettings.java, src/main/java/com/artipie/api/ArtipieApi.java, src/main/java/com/artipie/http/RtIsDashboard.java, src/main/java/com/artipie/http/SliceByPath.java, src/test/java/com/artipie/YamlSettingsTest.java, src/test/java/com/artipie/http/DockerRoutingSliceTest.java
=> #586 - Layout extracted

pom.xml, src/main/java/com/artipie/api/ArtipieApi.java, src/test/java/com/artipie/ArtipieServer.java, src/test/java/com/artipie/api/ArtipieApiITCase.java
Closes #775 
Added test from `ArtipieApi` and dashboard `GET` endpoints.
=> #775 - test for ArtipieApi

src/test/java/com/artipie/ArtipieServer.java, src/test/java/com/artipie/api/ArtipieApiITCase.java
Closes #803 
Added layout to `ArtipieServer` as a field.
=> #803 - specify layout on start

src/main/java/com/artipie/RepoConfig.java, src/main/java/com/artipie/VertxMain.java, src/test/java/com/artipie/ArtipieServer.java, src/test/java/com/artipie/VertxMainITCase.java, src/test/java/com/artipie/VertxMainTest.java
Part of #804 
Handle exception when parsing repo config on start
=> #804 - handle exception on repo config parsing

src/main/java/com/artipie/RepoPermissionsFromStorage.java, src/main/java/com/artipie/StorageAliases.java, src/main/java/com/artipie/UsersFromStorageYaml.java, src/main/java/com/artipie/repo/ConfigFile.java, src/test/java/com/artipie/RepoConfigYaml.java, src/test/java/com/artipie/RepoPermissionsFromSettingsTest.java, src/test/java/com/artipie/UsersFromStorageYamlTest.java
Part of #797
Use `ConfigFile` where `RxStorageWrapper` is used
=> #797 - Use ConfigFile where RxStorage is used for config files

src/main/java/com/artipie/Settings.java, src/main/java/com/artipie/VertxMain.java, src/main/java/com/artipie/YamlSettings.java, src/main/java/com/artipie/http/ArtipieRepositories.java, src/test/java/com/artipie/ArtipieServer.java, src/test/java/com/artipie/VertxMainITCase.java, src/test/java/com/artipie/YamlSettingsTest.java, src/test/java/com/artipie/http/DockerRoutingSliceTest.java
Part of #804 
Added setting for repositories configs location
=> #804 - Add setting for repo configs location

README.md
Closes #804 
Added info about new setting to readme
=> #804 - update readme

src/test/java/com/artipie/pypi/PypiITCase.java, src/test/java/com/artipie/test/TestContainer.java
Closes #826 
Made output for integration tests more verbose by refactoring `TestContainer`
=> #826 - Verbose output for IT cases

pom.xml, src/main/java/com/artipie/SliceFromConfig.java, src/main/java/com/artipie/docker/DockerPermissions.java, src/main/java/com/artipie/docker/DockerProxy.java, src/test/java/com/artipie/docker/DockerPermissionsTest.java
Closes #832 
Upgraded docker-adapter to 0.11
=> #832 - Upgraded docker-adapter to 0.11

src/test/java/com/artipie/ArtipieServer.java, src/test/java/com/artipie/debian/DebianAuthITCase.java
Part of #835 
Added debian test with auth
=> #835 - Auth test

.github/workflows/proof-binary.yaml, pom.xml, src/main/java/com/artipie/SliceFromConfig.java
Closes #840 
NuGet adapter upgraded to 0.5
=> #840 - NuGet adapter upgraded to 0.5

examples/npm/.gitignore, examples/npm/run.sh, pom.xml
#843 - updated npm and parent pom, fixed `run.sh` for npm and tested dist-tags, unpublish, deprecate
=> Updated npm, fixed run.sh

.github/workflows/proof-binary.yaml, pom.xml, src/main/java/com/artipie/SliceFromConfig.java
=> #843 - update adapters

src/main/java/com/artipie/Layout.java, src/test/java/com/artipie/LayoutFlatTest.java
#788
- Unit tests for `Layout.Flat`
=> (#788) Add unit tests for Layout.Flat

pom.xml
Updated docker-adapter and asto.
=> #0 - updated docker-adapter and asto

pom.xml, src/test/java/com/artipie/maven/MavenITCase.java, src/test/java/com/artipie/test/TestDeployment.java, src/test/resources/artipie.yaml, src/test/resources/helloworld-src/pom.xml, src/test/resources/helloworld-src/src/main/java/com/artipie/App.java, src/test/resources/maven-settings.xml, src/test/resources/maven.yml, src/test/resources/snapshot-src/pom.xml, src/test/resources/snapshot-src/src.main.java.com.artipie/App.java
For #855 - implemented Maven test based on testcontainers:
- Started Artipie docker image container
- Started Maven client container
- Initialize repository on Artipie container for download
- Download dependency from Artipie container
- Disabled deploy test, since Maven deploy doesn't work
=> Added maven integration test

README.md, src/main/java/com/artipie/JavaResource.java, src/main/java/com/artipie/VertxMain.java, src/main/resources/example/artipie.yaml
Fixes #864 - fixed standard resources copying on first start of
empty server, updated documentation.
=> Fixed new server autoconfiguration, updated README

Dockerfile, src/test/java/com/artipie/itcase/BinaryITCase.java, src/test/java/com/artipie/itcase/package-info.java, src/test/java/com/artipie/maven/MavenITCase.java, src/test/java/com/artipie/test/TestDeployment.java, src/test/resources/itcase/bin.yml
For #855 - added tests for upload and download for binary repository,
introduced new methods for working with `TestDeployment`,
fixed users and groups in Dockerfile for AccessDeniedException on write
in container.
=> Added integration test for binary repository

.github/workflows/integration-tests.yml, src/test/java/com/artipie/docker/DockerLocalAuthIT.java, src/test/java/com/artipie/nuget/NugetITCase.java, src/test/java/com/artipie/pypi/PypiProxyITCase.java, src/test/java/com/artipie/rpm/RpmITCase.java, src/test/resources/rpm/my-rpm.yml
Part of #855 
Remade IT for rpm to use `TestDeployment`
=> IT for rpm with TestDeployment

pom.xml, src/main/java/com/artipie/JavaResource.java, src/main/java/com/artipie/VertxMain.java, src/main/java/com/artipie/YamlStorage.java, src/main/java/com/artipie/repo/ConfigFile.java
Closes #879 - parse yaml etcd storage configuration
and build a client for etcd cluster, changed bootstrap configuration
in main to fill empty any kind of storage, not only FS.
=> Added etcd storage config

pom.xml, src/test/java/com/artipie/maven/MavenITCase.java
Closes #860 
I've updated maven and http and enabled maven IT.
=> Updated maven-adapter and enabled test

pom.xml, src/main/java/com/artipie/SliceFromConfig.java
=> Updated npm-adapter

src/test/java/com/artipie/api/ArtipieApiITCase.java, src/test/java/com/artipie/test/TestDeployment.java, src/test/resources/_permissions.yaml
For #896 - reproduced with integration test the issue when
update repo API hangs forever, disabled the test.
=> Reproduced update repo API issue

pom.xml, src/test/java/com/artipie/api/ArtipieApiITCase.java, src/test/resources/artipie_org.yaml
Closes #896 
Updated `management-api` and `asto`, corrected `ArtipieApiITCase`.
=> Updated management-api and corrected test

pom.xml
Related to https://github.com/artipie/management-api/issues/39
Updated `management-api` to 0.4.6
=> Updated management-api

.wiki/Configuration-Repository.md
For #869 - added `file` and `file-proxy` descriptions with examples.
=> Described file and file-proxy repo

.wiki/Configuration-Storage.md
For #860 - described FS and S3 storages, added todo for others, described default storages
=> Storage documentation

pom.xml, src/main/java/com/artipie/SliceFromConfig.java
Update version of Helm to `v1.0`
=> Bump helm to `v1.0`

src/main/java/com/artipie/repo/YamlCacheStorage.java, src/test/java/com/artipie/repo/YamlCacheStorageTest.java
Closes #334 
Added test for `YamlCacheStorage` for different possible cases
=> test: added test for `YamlCacheStorage`

pom.xml, src/main/java/com/artipie/SliceFromConfig.java, src/test/java/com/artipie/gem/GemITCase.java
=> Upgrade used gem adapter version

.github/workflows/integration-tests.yml, pom.xml, src/test/java/com/artipie/helm/HelmITCase.java, src/test/resources/helm/my-helm.yml
Part of #855 
Remade IT for helm to use `TestDeployment` and bumped helm to `v1.1.1`
=> ci: use docker container in `HelmITCase` and bumped helm to `v1.1.1`

examples/conda/README.md, src/main/java/com/artipie/conda/CondaConfig.java, src/main/java/com/artipie/conda/package-info.java, src/test/java/com/artipie/conda/CondaConfigTest.java
Part of #946 
Added anaconda configuration and updated repo `readme.md`
=> Added anaconda configuration

pom.xml, src/main/java/com/artipie/QuartzScheduler.java, src/main/java/com/artipie/SliceFromConfig.java, src/main/java/com/artipie/VertxMain.java, src/main/java/com/artipie/conda/CondaQuartz.java, src/main/java/com/artipie/repo/QuartzRepoJob.java, src/test/java/com/artipie/conda/CondaITCase.java
Part of #946 
Added `quartz` dependency, scheduler and job for anaconda. Also, updated `http`, `asto` and `conda` adapter.
=> Added quartz scheduler and conda job

src/test/java/com/artipie/maven/MavenMultiProxyIT.java, src/test/resources/maven/maven-multi-proxy.yml
Remade `MavenMultiProxyIT` to use Artipie docker images instead of `ArtipieServer`.
=> Used Artipie docker image in `MavenMultiProxyIT`

src/main/java/com/artipie/cache/CachedCreds.java, src/test/java/com/artipie/UsersFromStorageYamlTest.java, src/test/java/com/artipie/YamlSettingsTest.java, src/test/java/com/artipie/cache/CachedCredsTest.java
Part of #87 
Added more tests for credentials cache
=> test: add more tests for creds cache

.pdd
this pr fixes pdd issue about this [todo](https://github.com/artipie/artipie/blob/master/src/main/java/com/artipie/YamlSettings.java#L29) which has 16 only words although the minimum words for todo is 20.
the another solution would be increasing words of the todo.
=> decrease min-words from 20 to 16

src/test/java/com/artipie/docker/DockerLocalITCase.java, src/test/java/com/artipie/docker/DockerProxyIT.java, src/test/java/com/artipie/test/TestDeployment.java
Closes #1010 
- created docker test builder `com.artipie.test.TestDeployment.DockerTest`
- `DockerProxyIT` and `DockerLocalITCase` migrated to docker test builder
=> test: docker test builder

pom.xml
Apply https://github.com/artipie/http/pull/442 shared threadpool in multipart SDK: updated http, conda and python adapters.
=> fix: use shared threadpool in multipart

src/test/java/com/artipie/conda/CondaITCase.java
=> fix: enable CondaITCase.java

src/main/resources/example/artipie.yaml
Reverted main storage path in the example config.
=> fix: revert path in example config

.github/workflows/release.yml
Part of #1022 
Include jar file into release assets.
=> feat: add jar file to release assets

examples/run.sh
Improving smoking tests stability.
It quite stable now for both local/partial and full/GitHub runs.
See also: https://github.com/artipie/artipie/issues/1037
=> Improving smoking tests stability

src/test/java/com/artipie/debian/DebianITCase.java, src/test/java/com/artipie/gem/GemITCase.java, src/test/resources/debian/debian-port.yml, src/test/resources/debian/sources.list, src/test/resources/gem/gem-port.yml
Closes #1043 Closes #1050
Extended GemITCase and DebianITCase with cases with individual repository ports.
=> fix: extended GemITCase and DebianITCase

pom.xml, src/main/java/com/artipie/file/FileProxy.java, src/test/java/com/artipie/file/FileProxyAuthIT.java, src/test/resources/binary/bin-proxy-cache.yml
closes #1056 
Updated files-adapter, enabled cache feature for proxy and added corresponding case into IT.
=> feat: updated files-adapter and enabled cache feature

src/test/java/com/artipie/composer/PhpComposerITCase.java, src/test/java/com/artipie/helm/HelmITCase.java, src/test/resources/composer/composer-port.json, src/test/resources/composer/php-port.yml, src/test/resources/helm/my-helm-port.yml
Closes #1052 and #1044
Added ITs  with individual port for Php and Helm
=> fix: IT with individual port for Php and Helm

.wiki/Home.md, src/main/resources/example/repo/test/maven-group.yaml, src/main/resources/example/repo/test/maven-proxy.yaml
Closes: #1059 
- written section `how to start artipie with maven-proxy repository`
- fixed maven-proxy example files
=> doc: how to start artipie with maven-proxy repository

src/test/java/com/artipie/pypi/PypiITCase.java, src/test/resources/pypi-repo/pypi-port.yml
@olenagerasimova Please review fix for #1051 
closes: #1051
=> fix: extended PypiITCase to test individual repository port

src/test/java/com/artipie/rpm/RpmITCase.java, src/test/resources/rpm/my-rpm-port.yml
=> fix: extended RpmITCase to test individual repository port

.wiki/Configuration-Credentials.md
Part of #1031 
Added detailed description for credentials.
=> doc: added credentials description

src/test/java/com/artipie/npm/NpmITCase.java, src/test/resources/npm/npm-port.yml
=> fix: extended NpmITCase to test individual repository port

.wiki/Configuration-Repository.md
Part of #1031 
Added general description for repository configs. Each repository will be described letter
=> doc: repo configs

src/test/java/com/artipie/maven/MavenMultiProxyIT.java, src/test/resources/maven/maven-multi-proxy-port.yml
closes: #1047
@olenagerasimova Could you please to review?
=> fix: extended MavenMultiProxyIT to test individual repository port

src/test/java/com/artipie/nuget/NugetITCase.java, src/test/resources/nuget/nuget-port.yml
closes: #1045
@olenagerasimova Could you please to review?
=> fix: extended NugetITCase to test individual repository port

src/test/java/com/artipie/conda/CondaITCase.java, src/test/resources/conda/conda-port.yml, src/test/resources/conda/condarc-port
closes: #1049
@olenagerasimova Could you please to review?
=> fix: extended CondaITCase to test individual repository port

.wiki/Configuration-Metrics.md, .wiki/Configuration-Repository.md
Part of #1031 
Extended metrics section, but I do not know all the details. As these settings do not seem to be necessary to start working with Artipie, I've added todo to verify them later.
=> doc: metrics

pom.xml, src/main/java/com/artipie/YamlStorage.java
Closes: #1034
- obtaining instance of storage using class `Storages`
=> feat: ability to plug in a custom storage

pom.xml, src/test/java/com/artipie/UsersFromStorageYamlTest.java, src/test/java/com/artipie/docker/DockerLocalAuthIT.java
Closes: #1093
- removed `wtf.g4s8:tuples` dependency
- moved dependencies with test scope to one place
=> Remove `wtf.g4s8:tuples`

pom.xml
=> dep: updated adapters

src/main/java/com/artipie/api/RepositoryVerticle.java, src/test/java/com/artipie/api/RepositoryVerticleTest.java, src/test/java/com/artipie/api/package-info.java
part of #1099 
Added test for RepositoryVerticle
=> feat: added test for RepositoryVerticle

pom.xml, src/main/java/com/artipie/api/ManageStorageAliases.java, src/main/java/com/artipie/misc/Json2Yaml.java, src/main/java/com/artipie/misc/Yaml2Json.java, src/main/java/com/artipie/settings/CrudStorageAliases.java, src/test/java/com/artipie/api/ManageStorageAliasesTest.java
Part of #1099 
Moved from front interface and implementation to manage storage aliases
=> feat: crud for storage aliases

pom.xml, src/main/java/com/artipie/api/StorageAliasesRest.java, src/main/resources/swagger-ui/yaml/org.yaml, src/test/java/com/artipie/api/RestApiServerBase.java, src/test/java/com/artipie/api/StorageAliasesRestFlatTest.java, src/test/java/com/artipie/api/StorageAliasesRestOrgTest.java
Part of #1099 
Added endpoints to list aliases for org layouts and tests.
=> feat: list aliases for org layout

src/main/java/com/artipie/api/StorageAliasesRest.java, src/main/resources/swagger-ui/yaml/flat.yaml, src/main/resources/swagger-ui/yaml/org.yaml, src/test/java/com/artipie/api/StorageAliasesRestFlatTest.java, src/test/java/com/artipie/api/StorageAliasesRestOrgTest.java
part of #1099
Added endpoints to add/update aliases
=> feat: add/update aliases

src/main/java/com/artipie/api/BaseRest.java, src/main/java/com/artipie/api/ManageRepoSettings.java, src/main/java/com/artipie/api/RepositoryName.java, src/main/java/com/artipie/api/RepositoryRest.java, src/main/java/com/artipie/api/StorageAliasesRest.java, src/main/java/com/artipie/api/ValidRepositoryName.java, src/main/java/com/artipie/settings/RepoData.java, src/main/java/com/artipie/settings/repo/CrudRepoSettings.java, src/test/java/com/artipie/settings/RepoDataTest.java
close: #1120 
feat: 
Add RepoData functionality defined in artipie/front.
Add implementation of 'ManageRepoSettings.delete'
@olenagerasimova @dgarus Please review PR
=> feat: Add RepoData functionality defined in artipie/front.

src/main/java/com/artipie/api/StorageAliasesRest.java, src/main/resources/swagger-ui/yaml/flat.yaml, src/main/resources/swagger-ui/yaml/org.yaml, src/test/java/com/artipie/api/StorageAliasesRestFlatTest.java, src/test/java/com/artipie/api/StorageAliasesRestOrgTest.java
Part of #1099 
Added endpoints to delete aliases
=> feat: added endpoints to delete aliases

src/main/java/com/artipie/VertxMain.java, src/main/java/com/artipie/api/RestApi.java, src/main/java/com/artipie/api/StorageAliasesRest.java, src/main/java/com/artipie/settings/SettingsFromPath.java, src/main/java/com/artipie/settings/cache/StorageConfigCache.java, src/test/java/com/artipie/api/RestApiServerBase.java, src/test/java/com/artipie/api/StorageAliasesRestFlatTest.java, src/test/java/com/artipie/api/StorageAliasesRestOrgTest.java, src/test/java/com/artipie/settings/SettingsFromPathTest.java
Part of #1099 
Added storage settings cache reload feature to aliases endpoint
=> feat: reload caches when aliases are changed

src/main/java/com/artipie/api/ManageUsers.java, src/main/java/com/artipie/settings/YamlSettings.java, src/main/java/com/artipie/settings/users/CrudUsers.java, src/test/java/com/artipie/api/ManageUsersTest.java
Part of #1099 
Added functionality for user's CRUD operations
=> feat: classes for users CRUD operations

src/main/java/com/artipie/api/ConfigKeys.java, src/main/java/com/artipie/api/ManageRepoSettings.java, src/main/java/com/artipie/api/RepositoryRest.java, src/main/java/com/artipie/settings/repo/CrudRepoSettings.java, src/test/java/com/artipie/api/RepositoryRestFlatTest.java, src/test/java/com/artipie/api/RepositoryRestOrgTest.java
close: #1129 
@olenagerasimova @dgarus Please review
=> feat: add checking of repository settings duplicates

.wiki/Configuration-Storage.md, README.md
part of [445](https://github.com/artipie/asto/issues/445)
Added a verification tests description to the storage section.
=> doc: verification tests

.wiki/repositories/anaconda.md, .wiki/repositories/composer.md, .wiki/repositories/debian.md, .wiki/repositories/docker.md, .wiki/repositories/file.md, .wiki/repositories/gem.md, .wiki/repositories/go.md, .wiki/repositories/helm.md, .wiki/repositories/hexpm.md, .wiki/repositories/npm-proxy.md, .wiki/repositories/npm.md, .wiki/repositories/pypi-proxy.md, .wiki/repositories/pypi.md, .wiki/repositories/rpm.md
close: #1137
@olenagerasimova @Swizbiz @dgarus could you please to review?
=> fix: Broken links on wiki pages #1137

src/main/java/com/artipie/api/UsersRest.java, src/main/resources/swagger-ui/yaml/users.yaml, src/test/java/com/artipie/api/UsersRestTest.java
Part pf #1099 
Added endpoint to remove user
=> feat: delete user endpoint

src/main/java/com/artipie/api/BaseRest.java, src/main/java/com/artipie/api/ManageRepoSettings.java, src/main/java/com/artipie/api/RepositoryRest.java, src/main/java/com/artipie/api/Validator.java, src/main/java/com/artipie/api/verifier/ExistenceVerifier.java, src/main/java/com/artipie/api/verifier/ReservedNamesVerifier.java, src/main/java/com/artipie/api/verifier/SettingsDuplicatesVerifier.java, src/main/java/com/artipie/api/verifier/package-info.java, src/main/java/com/artipie/settings/repo/CrudRepoSettings.java, src/main/resources/swagger-ui/yaml/flat.yaml, src/main/resources/swagger-ui/yaml/org.yaml, src/test/java/com/artipie/api/RepositoryRestBaseTest.java, src/test/java/com/artipie/api/RepositoryRestFlatTest.java, src/test/java/com/artipie/api/RepositoryRestOrgTest.java
close: #1141 
@olenagerasimova @dgarus Please review
=> feat: Add 'move'-repository for rest-api

pom.xml
close: #1144
@olenagerasimova @dgarus Please review
=> feat: Increase version in pom for com.artipie:npm-adapter

src/main/java/com/artipie/api/BaseRest.java, src/main/java/com/artipie/api/RestApi.java, src/main/resources/swagger-ui/yaml/repo-flat.yaml, src/main/resources/swagger-ui/yaml/repo-org.yaml, src/main/resources/swagger-ui/yaml/token-gen.yaml, src/main/resources/swagger-ui/yaml/users.yaml, src/test/java/com/artipie/api/AuthRestOrgTest.java, src/test/java/com/artipie/api/AuthTokenRestTest.java, src/test/java/com/artipie/api/RestApiServerBase.java
Part to #1099 
Added authentication for API endpoints. More tests will be added in the next PR
=> feat: added authentication

src/main/java/com/artipie/api/RepositoryRest.java, src/main/java/com/artipie/api/Validator.java, src/main/java/com/artipie/api/verifier/ExistenceVerifier.java, src/main/java/com/artipie/api/verifier/ReservedNamesVerifier.java, src/main/java/com/artipie/api/verifier/SettingsDuplicatesVerifier.java, src/main/java/com/artipie/api/verifier/Verifier.java, src/main/resources/swagger-ui/yaml/repo-flat.yaml, src/main/resources/swagger-ui/yaml/repo-org.yaml, src/test/java/com/artipie/api/RepositoryRestBaseTest.java, src/test/java/com/artipie/api/RepositoryRestFlatTest.java, src/test/java/com/artipie/api/RepositoryRestOrgTest.java
close #1146
@olenagerasimova, @dgarus Please review
=> feat: check existing of repo for rest-api

src/test/java/com/artipie/api/AuthRestFlatTest.java, src/test/java/com/artipie/api/RestApiServerBase.java
Part of #1099 
Added more tests for authentication.
=> feat: added more tests for authentication

.wiki/Configuration-Metrics.md, .wiki/Home.md, pom.xml, src/main/java/com/artipie/VertxMain.java, src/main/java/com/artipie/metrics/MetricsFromConfig.java, src/main/resources/example/artipie.yaml, src/test/java/com/artipie/metrics/MetricsFromConfigTest.java
Part of #1006 
Added Vert.x metrics and now it's possible to configure several metrics types at ones.
=> feat: Vert.x metrics

src/main/java/com/artipie/api/RepositoryRest.java, src/main/resources/swagger-ui/yaml/repo-flat.yaml, src/main/resources/swagger-ui/yaml/repo-org.yaml, src/test/java/com/artipie/api/RepositoryRestBaseTest.java, src/test/java/com/artipie/api/RepositoryRestFlatTest.java, src/test/java/com/artipie/api/RepositoryRestOrgTest.java
Closes: #1169 
@olenagerasimova, @dgarus Please review
=> feat: Provide 'update repository' settengs functionality for REST API

src/main/java/com/artipie/api/RepositoryRest.java, src/test/java/com/artipie/api/RepositoryRestBaseTest.java, src/test/java/com/artipie/api/RepositoryRestFlatTest.java, src/test/java/com/artipie/api/RepositoryRestOrgTest.java
Closes: #1177
@olenagerasimova Please review
=> fix: Removing repostitory via REST-api should remove repository with wrong configuration

.wiki/DockerCompose.md, .wiki/_Sidebar.md, docker-compose.yaml
- docker-compose file to up Artipie backend and frontend
- wiki page with docker-compose's quickstart
=> feat: Quickstart with docker-compose

src/main/java/com/artipie/jfr/StorageCreateEvent.java, src/main/java/com/artipie/settings/cache/CachedStorages.java, src/test/java/com/artipie/jfr/StorageCreateEventTest.java
close #1192 
- added `StorageCreateEvent`, usage and test
=> storage create event

src/main/java/com/artipie/http/BaseSlice.java, src/main/java/com/artipie/jfr/AbstractStorageEvent.java, src/main/java/com/artipie/jfr/ChunksAndSizeMetricsPublisher.java, src/main/java/com/artipie/jfr/JfrSlice.java, src/main/java/com/artipie/jfr/JfrStorage.java, src/main/java/com/artipie/jfr/SliceResponseEvent.java, src/main/java/com/artipie/jfr/StorageCreateEvent.java, src/main/java/com/artipie/jfr/StorageSaveEvent.java, src/main/java/com/artipie/jfr/StorageValueEvent.java, src/main/java/com/artipie/settings/cache/CachedStorages.java, src/test/java/com/artipie/jfr/JfrSliceTest.java
closes #1202 
- added `SliceResponseEvent` and `JfrSlice`
- implemented `JfrSliceTest` to check `JfrSlice`
=> JFR event for http request

.wiki/_Sidebar.md
=> Remove `Logging metrics` and `Storage metrics` menu items

.wiki/_Sidebar.md, .wiki/jfr-events.md, src/main/java/com/artipie/jfr/SliceResponseEvent.java, src/main/java/com/artipie/jfr/StorageDeleteAllEvent.java, src/main/java/com/artipie/jfr/StorageExistsEvent.java
closes #1203 
- added Artipie's JFR events section
=> wiki: describe Artipie's JFR events

.github/workflows/maven-central.yml
Fix deploy errors: --add-opens=java.base/java.util
Part of https://github.com/artipie/artipie/issues/1206
=> Fix deploy errors: --add-opens=java.base/java.util

pom.xml, src/main/java/com/artipie/api/AuthTokenRest.java, src/main/java/com/artipie/api/RestApi.java, src/main/java/com/artipie/auth/JwtTokens.java, src/test/java/com/artipie/auth/JwtTokensTest.java
Part of #1227 
Implemented `com.artipie.http.auth.Tokens` interface, added test and used it in rest api (so tokens are generated in one place).
=> feat: generate tokens

pom.xml
Relates: #1244
This PR's branch is based on 'tag: v0.28.1' and adds asto deps
It is assummed that new tag will be created with asto deps.
=> Add asto deps

src/main/java/com/artipie/api/ManageUsers.java, src/main/java/com/artipie/api/RestApi.java, src/main/java/com/artipie/api/UsersRest.java, src/main/java/com/artipie/settings/users/CrudUsers.java, src/main/resources/swagger-ui/yaml/users.yaml, src/test/java/com/artipie/api/AuthRestFlatTest.java, src/test/java/com/artipie/api/AuthRestOrgTest.java, src/test/java/com/artipie/api/AuthTokenRestTest.java, src/test/java/com/artipie/api/ManageUsersTest.java, src/test/java/com/artipie/api/RestApiServerBase.java, src/test/java/com/artipie/api/SSLBaseRestTest.java, src/test/java/com/artipie/api/UsersRestTest.java
part of #1237 
Corrected users rest api to comply with new users yamls structure. Also, added methods to enable and disable users.
=> feat: re-implement users rest api

src/main/resources/example/security/roles/reader.yml, src/main/resources/example/security/users/artipie.yaml
part of #1237 
fixed example configs format
=> fix: correct example config files

.wiki/repositories/docker.md, .wiki/repositories/file-proxy-mirror.md, .wiki/repositories/maven-proxy.md
part of https://github.com/artipie/http/issues/501
=> Remove permissions section from repo config

.wiki/Configuration-Credentials.md
part of #1262 
added description for custom authentication
=> wiki: added custom auth description

src/main/java/com/artipie/settings/SettingsFromPath.java
part of #1237 
Fixed resources copy process in `SettingsFromPath`: as we now have different storages for repo settings and security, it's necessary to copy resources correspondingly.
=> fix: copy example resources into different storages

.wiki/Configuration-Repository.md
=> Wiki documentation for repository filters

pom.xml, src/main/java/com/artipie/http/DockerRoutingSlice.java, src/main/java/com/artipie/settings/YamlSettings.java, src/main/java/com/artipie/settings/cache/CachedStorages.java, src/test/java/com/artipie/http/DockerRoutingSliceTest.java
part of #1237 
Create storages loader instance only once in artipie/artipie
=> fix: single storages loader

.wiki/_Sidebar.md
=> Add "Filters" link to sidebar

.wiki/Configuration-Storage.md
=> Changing the S3 storage wiki doc

pom.xml
=> bump up asto and http versions

pom.xml, src/main/java/com/artipie/db/ArtifactDbFactory.java, src/main/java/com/artipie/db/package-info.java, src/test/java/com/artipie/db/ArtifactDbTest.java, src/test/java/com/artipie/db/package-info.java
part of #1291 
Added class to initialize database.
=> feat: init db

.github/workflows/perftest-client.yml, .github/workflows/perftest-server.yml
Report perftests performance differences via emails. Part of https://github.com/artipie/benchmarks/issues/64
=> Report perftests performance differences via emails

.wiki/Configuration-Scripting.md, .wiki/_Sidebar.md
Documentation for Artipie scripting support. Part of https://github.com/artipie/artipie/issues/1277
=> Documentation for Artipie scripting support

pom.xml, src/main/java/com/artipie/SliceFromConfig.java, src/main/java/com/artipie/VertxMain.java, src/main/java/com/artipie/adapters/docker/DockerProxy.java, src/main/java/com/artipie/adapters/file/FileProxy.java, src/main/java/com/artipie/adapters/maven/MavenProxy.java, src/main/java/com/artipie/adapters/pypi/PypiProxy.java, src/main/java/com/artipie/api/RepositoryRest.java, src/main/java/com/artipie/api/RestApi.java, src/main/java/com/artipie/db/DbConsumer.java, src/main/java/com/artipie/scheduling/MetadataEventQueues.java, src/main/java/com/artipie/scheduling/QuartzService.java, src/main/java/com/artipie/scheduling/ScriptScheduler.java, src/main/java/com/artipie/settings/Settings.java, src/main/java/com/artipie/settings/SettingsFromPath.java, src/main/java/com/artipie/settings/YamlSettings.java, src/test/java/com/artipie/SchedulerDbTest.java, src/test/java/com/artipie/api/RestApiServerBase.java, src/test/java/com/artipie/auth/AuthFromKeycloakTest.java, src/test/java/com/artipie/db/DbConsumerTest.java, src/test/java/com/artipie/docker/DockerProxyTest.java, src/test/java/com/artipie/http/DockerRoutingSliceTest.java, src/test/java/com/artipie/scheduling/MetadataEventQueuesTest.java, src/test/java/com/artipie/scheduling/QuartzServiceTest.java, src/test/java/com/artipie/scheduling/ScriptSchedulerTest.java, src/test/java/com/artipie/settings/SettingsFromPathTest.java, src/test/java/com/artipie/settings/YamlSettingsTest.java, src/test/java/com/artipie/settings/cache/CachedStoragesTest.java, src/test/java/com/artipie/settings/repo/RepoConfigYaml.java, src/test/java/com/artipie/test/TestSettings.java
part of #1291 
Updated all the adapters and added `MetadataEventQueues` to work with jobs and queues for proxy-adapters. Please, check, let's discuss if something is not clear and then I'll add more tests and description.
=> feat: artifacts metadata event queues

.github/workflows/docker-release.yml, .github/workflows/maven-adapter-release.yml, maven-adapter/src/test/java/com/artipie/maven/MavenProxyPackageProcessorTest.java
Correct release scripts and increased timeout in the test (github actions are slow)
=> fix: correct release scripts

.github/workflows/docker-release.yml, .github/workflows/maven-adapter-release.yml
=> fix: correct github actions

artipie-main/src/main/resources/example/repo/my-maven.yaml
corrected example repository settings
=> fix: correct example repo

artipie-core/pom.xml, artipie-core/src/main/java/com/artipie/http/servlet/ServletConnection.java, artipie-core/src/main/java/com/artipie/http/servlet/ServletSliceWrap.java, artipie-core/src/main/java/com/artipie/http/servlet/package-info.java, artipie-core/src/test/java/com/artipie/http/servlet/ServletWrapITCase.java, artipie-core/src/test/java/com/artipie/http/servlet/package-info.java
ServletSliceWrap is used in CloudArtifact, so I've reverted it
=> Rollback ServletSliceWrap

.github/workflows/integration-tests.yml, artipie-core/src/main/java/com/artipie/security/perms/UserPermissions.java, artipie-main/src/main/java/com/artipie/api/RestApi.java, artipie-main/src/test/java/com/artipie/docker/DockerLocalAuthIT.java, artipie-main/src/test/java/com/artipie/docker/DockerLocalITCase.java, artipie-main/src/test/java/com/artipie/docker/DockerOnPortIT.java, artipie-main/src/test/java/com/artipie/docker/DockerProxyIT.java, artipie-main/src/test/java/com/artipie/test/TestDockerClient.java, artipie-main/src/test/java/com/artipie/test/vertxmain/MetaBuilder.java, artipie-main/src/test/java/com/artipie/test/vertxmain/TestVertxMain.java, artipie-main/src/test/java/com/artipie/test/vertxmain/TestVertxMainBuilder.java, artipie-main/src/test/resources/Dockerfile, artipie-main/src/test/resources/docker/Dockerfile, artipie-main/src/test/resources/security/users/alice.yaml, asto/asto-core/src/main/java/com/artipie/asto/test/TestResource.java, build-tools/src/main/resources/pmd-ruleset.xml, docker-adapter/src/main/java/com/artipie/docker/http/AuthScopeSlice.java, docker-adapter/src/main/java/com/artipie/docker/http/DockerSlice.java, docker-adapter/src/main/java/com/artipie/docker/perms/DockerRegistryPermission.java, docker-adapter/src/main/java/com/artipie/docker/perms/DockerRepositoryPermission.java
Part of #1352
- added `TestVertxMainBuilder` Artipie's server builder for tests
- added the `TestDockerClient` based on the `dgarus/test-docker-client:1.0` image
- rewrote docker integration tests with `TestVertxMainBuilder` and `TestDockerClient`
=> feat: Improving docker integration tests

artipie-main/pom.xml, asto/asto-s3/pom.xml, asto/asto-s3/src/main/java/com/artipie/asto/s3/S3StorageFactory.java, asto/asto-s3/src/test/java/com/artipie/asto/S3StorageWhiteboxVerificationTest.java, asto/asto-s3/src/test/java/com/artipie/asto/s3/BucketTest.java, debian-adapter/pom.xml, http-client/pom.xml, pom.xml, pypi-adapter/pom.xml, rpm-adapter/pom.xml
Updating s3 and jetty deps. Reduce potential conflicts over jetty, vulnerabilities and AWS compatibility issues.
=> Updating s3 and jetty deps

.wiki/Configuration-Metadata.md, .wiki/Configuration.md, .wiki/Home.md, .wiki/repositories/docker-proxy.md, .wiki/repositories/file-proxy-mirror.md, .wiki/repositories/maven-proxy.md, .wiki/repositories/npm-proxy.md, .wiki/repositories/pypi-proxy.md, README.md
=> feat: update wiki pages

artipie-main/src/test/java/com/artipie/debian/DebianS3ITCase.java
Extra S3 deb test via curl PUT.
=> Extra S3 deb test via curl PUT

artipie-main/src/test/java/com/artipie/debian/DebianS3ITCase.java, artipie-main/src/test/java/com/artipie/rpm/RpmS3ITCase.java, asto/asto-core/src/main/java/com/artipie/asto/misc/UncheckedScalar.java, debian-adapter/src/test/java/com/artipie/debian/DebianSliceS3ITCase.java, rpm-adapter/src/test/java/com/artipie/rpm/http/RpmSliceS3ITCase.java
Removed checkstyle from Artipie.
=> Removed checkstyle from Artipie

rpm-adapter/pom.xml, rpm-adapter/src/test/java/com/artipie/rpm/http/RpmSliceS3ITCase.java
Test was failing due to dependency issues: https://github.com/artipie/artipie/issues/1409
=> Test was failing due to dependency issues

.wiki/Configuration-Scripting.md, artipie-main/pom.xml, artipie-main/src/main/java/com/artipie/scripting/Script.java, artipie-main/src/test/java/com/artipie/scripting/ScriptingTest.java, debian-adapter/pom.xml, helm-adapter/pom.xml, pom.xml, rpm-adapter/pom.xml
Removed redundant dependencies. Updated dependencies and CVE fixes.
=> Removed redundant dependencies and CVE fixes

pom.xml
=> vert.x version 4.5.4

artipie-main/src/test/java/com/artipie/conan/ConanITCase.java, artipie-main/src/test/java/com/artipie/conan/ConanS3ITCase.java, artipie-main/src/test/resources/conan/conan-s3.yml
=> Conan S3 IT tests

artipie-main/src/test/java/com/artipie/jetty/http3/Http3ServerTest.java
Intermittent test fail fix in `Http3ServerTest`:
* Updated `onDataAvailable()` logic according to `Stream.Client.Listener` javadoc recommentations
* Updated assert message/logic to report fail in more precise and useful way (in case it will happen again)
* Refactored tests and extracted common logic to `StreamTestListener` class.
Fail log:
```
[INFO] Running com.artipie.jetty.http3.Http3ServerTest
[WARN] main org.eclipse.jetty.util.ssl.SslContextFactory.config: Trusting all certificates configured for Client@4fe89c24[provider=null,keyStore=null,trustStore=null]
[WARN] main org.eclipse.jetty.util.ssl.SslContextFactory.config: No Client EndPointIdentificationAlgorithm configured for Client@4fe89c24[provider=null,keyStore=null,trustStore=null]
[WARN] main …
```
=> Intermittent test fail fix in Http3ServerTest

artipie-core/pom.xml, artipie-core/src/main/java/com/artipie/http/servlet/ServletSliceWrap.java, artipie-core/src/main/java/com/artipie/http/slice/TrimPathSlice.java, artipie-main/pom.xml, conan-adapter/src/main/java/com/artipie/conan/http/ConansEntity.java, http-client/src/main/java/com/artipie/http/client/ProxySettings.java, http-client/src/main/java/com/artipie/http/client/jetty/JettyClientSlice.java, nuget-adapter/pom.xml, nuget-adapter/src/test/java/com/artipie/nuget/http/publish/NuGetPackagePublishTest.java, pom.xml, pypi-adapter/pom.xml
Updating apache httpclient to v5.x
=> Updating apache httpclient to v5.x

artipie-main/src/test/java/com/artipie/docker/DockerLocalS3ITCase.java, artipie-main/src/test/java/com/artipie/test/TestDockerClient.java, artipie-main/src/test/java/com/artipie/test/vertxmain/TestVertxMainBuilder.java, docker-adapter/pom.xml, docker-adapter/src/test/java/com/artipie/docker/http/DockerSliceS3ITCase.java
Basic Docker + S3 storage tests.
=> Basic Docker + S3 storage tests

gem-adapter/src/main/java/com/artipie/gem/GemApiKeyAuth.java
Fix possible crash. Backported fix from `origin/jdk17-builds`
=> Fix possible crash

npm-adapter/src/main/java/com/artipie/npm/http/AddDistTagsSlice.java, npm-adapter/src/main/java/com/artipie/npm/http/DeleteDistTagsSlice.java
Potential bug / intermittent test fail fix.
=> Potential intermittent test fail fix

debian-adapter/pom.xml, debian-adapter/src/main/java/com/artipie/debian/metadata/Release.java
before the fix:
after the fix:
=> Debian invalid date format fix

pypi-adapter/src/main/java/com/artipie/pypi/http/DeleteSlice.java, pypi-adapter/src/main/java/com/artipie/pypi/http/PySlice.java, pypi-adapter/src/test/java/com/artipie/pypi/http/DeleteSliceTest.java
pypi adapter - implementation of delete artifacts
=> pypi adapter - implementation of delete artifacts

asto/asto-s3/pom.xml
ASTO S3 - added aws sts dependency
=> ASTO S3 - added aws sts dependency
