artipie/artipie

- .pdd
- .rultor.yml
#7 - updated rultor image:
- using [g4s8/rultor-jdk11](https://github.com/g4s8/dockers/tree/master/rultor-jdk11) rultor image
- removed redundant installations step
- removed obsolete environment variables
- added `pdd` config
> Updated rultor image

- pom.xml
- src/main/java/com/artipie/YamlSettings.java
For #35: removed redundant methods for YamlSettings.
- Removed redundant methods from `YamlSetting`, which are already executed in `StrictYamlMapping`;
- Left question in issue about how `StrictYamlMapping` and `YamlMapping` should behave
> For #35: removed redundant methods for YamlSettings

- src/main/resources/log4j.properties
For now, when artipie is started, a huge amount of mess is thrown into a console:
```
$ docker run -v /tmp/artipie:/var/artipie -p80:80 artipie:local
APP main io.netty.util.internal.logging.InternalLoggerFactory: Using SLF4J as the default logging framework
APP main io.netty.util.ResourceLeakDetector: -Dio.netty.leakDetection.level: simple
APP main io.netty.util.ResourceLeakDetector: -Dio.netty.leakDetection.targetRecords: 4
APP main io.netty.util.internal.InternalThreadLocalMap: -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
APP main io.netty.util.internal.InternalThreadLocalMap: -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
APP main io.netty.channel.MultithreadEventLoopGroup: -Dio.netty.eventLoopThreads: 16
APP main io.netty.channel.nio.NioEventLoop: …
```
> Logging improvements

- src/main/java/com/artipie/RepoConfig.java
- src/main/java/com/artipie/SliceFromConfig.java
- src/test/java/com/artipie/RepoConfigTest.java
- src/test/resources/repo-full-config.yml
Part of #119
Support for `content-length-max` in repo config
> #119 - Support for content-length-max repo config param

- pom.xml
- src/main/java/com/artipie/ContentLengthRestriction.java
- src/test/java/com/artipie/ContentLengthRestrictionTest.java
Part of #119 
Response status code 413 when Content-Length is above limit instead of 400
> #119 - Response status code 413 when Content-Length is above limit

- .github/workflows/benchmarks.yaml
For https://github.com/artipie/benchmarks/issues/12.
Firstly, this PR is required to be merged:
https://github.com/artipie/benchmarks/pull/15
Then 2 secrets must be created in the artipie repo:
PERF_AWS_ACCESS_KEY 
PERF_AWS_SECRET_KEY
It's AWS credentials to create performance tests environment.
Then current PR can be merged
> implement job to start benchmarks on release

- README.md
- _config.yml
#182 - using `env` credentials by default
> Using env credentials by default

- _config.yml
- src/main/java/com/artipie/Pie.java
- src/main/java/com/artipie/RepoConfig.java
- src/main/java/com/artipie/Settings.java
- src/main/java/com/artipie/SliceFromConfig.java
- src/main/java/com/artipie/YamlSettings.java
- src/main/java/com/artipie/repo/FlatLayout.java
- src/main/java/com/artipie/repo/OrgLayout.java
- src/main/java/com/artipie/repo/RepoLayout.java
- src/main/java/com/artipie/repo/package-info.java
- src/test/java/com/artipie/RepoConfigTest.java
- src/test/java/com/artipie/YamlSettingsTest.java
#178 - support two different repository layout formats:
- `flat` - no repository hierarchy
- `org` - two level hierarchy: first level is organization name, second part is repository name
See `RepoLayout` javadoc for more details.
> Support hierarchical paths for repos

- pom.xml
- src/main/java/com/artipie/RepoConfig.java
- src/main/java/com/artipie/RpPermissions.java
- src/main/java/com/artipie/SliceFromConfig.java
- src/main/java/com/artipie/StorageAliases.java
- src/main/java/com/artipie/YamlSettings.java
- src/main/java/com/artipie/YamlStorage.java
- src/main/java/com/artipie/repo/FlatLayout.java
- src/main/java/com/artipie/repo/OrgLayout.java
- src/test/java/com/artipie/RepoConfigTest.java
- src/test/java/com/artipie/YamlStorageTest.java
#78 - using storage aliases for repo configuration. Refactored `RepoConfig` methods to be synchronous to avoid one more (5-th) callback parameter for constructing configuration. This feature helps to hide actual credentials from config and restrict user permissions to allow modify repository settings only without changing storage configuration (in case of Central).
> Using storage aliases

- src/main/java/com/artipie/http/DockerRoutingSlice.java
- src/main/java/com/artipie/http/Pie.java
- src/main/java/com/artipie/http/SliceByPath.java
- src/test/java/com/artipie/http/DockerRoutingSliceTest.java
- src/test/java/com/artipie/http/package-info.java
#274 - Programmatically normalize Docker `/v2` requests to Artipie path format: `/v2/repo/image` -> `/repo/image`.
> Normalize Docker paths

- pom.xml
- src/main/java/com/artipie/SliceFromConfig.java
Related to #188 
* Helm adapter version has been updated to version 0.1.3. 
* The repo name is removed from the request path.
> Bump helm adapter version

- examples/binary/configs/repo.yaml
Rollback accidentally deleted config file so the binary Proof would pass now.
Related to #154.
> Rollback accidentally deleted config file

- pom.xml
- src/main/java/com/artipie/SliceFromConfig.java
- src/main/java/com/artipie/docker/DockerProxy.java
Closes #385 
Added basic auth support for `docker` and `docker-proxy` repo types
> #385 - Authentication support for Docker repositories

- examples/README.md
> Fix typo: 'docker' -> 'go'

- src/main/java/com/artipie/MeasuredSlice.java
- src/main/java/com/artipie/MeasuredStorage.java
- src/main/java/com/artipie/RepoConfig.java
- src/main/java/com/artipie/YamlSettings.java
- src/main/java/com/artipie/http/Pie.java
- src/main/resources/log4j.properties
- src/test/java/com/artipie/YamlSettingsTest.java
#382 - added measured decorator for all slices and storages if debug logging enabled. It prints execution time of all reuqests and all IO operations with `DEBUG` level.
The result of this measurement: some upload requests can be fetched from HTTP connection about 2-3 seconds for Maven repository, e.g. this is the log for small checksum file upload (size = 32 bytes): next `ByteBuffer` was requested from subscribtion in `0ms`, received after `2996ms` and saved at `2996ms` (less than `1ms`), completed in `2997ms` (moved temporary file to destination in less than `2ms`)
```
[DEBUG] 2020-07-27 17:14:33,280 FileStorage-11 com.artipie.MeasuredStorage - save(com/artipie/sample-for-deployment/1.0/sample-for-deployment-1.0.pom.md5): onSubscribe(subscription=0) 0ms
[DEBUG] 2020-07-27 17:14:33,280 …
```
> Slices and storages measured decorator

- pom.xml
- src/main/java/com/artipie/ContinueSlice.java
- src/main/java/com/artipie/http/SliceByPath.java
#382 - added `Slice` decorator to check `Except` header for `100-continue` value, and sends `100` status after request head but before request body, see: https://github.com/artipie/vertx-server/pull/18
Waiting https://github.com/artipie/vertx-server/pull/18 to be merged and released
> Send continue response before actual response if expected

- src/main/java/com/artipie/api/ContentAs.java
- src/main/java/com/artipie/api/artifactory/CreateRepoSlice.java
- src/main/java/com/artipie/api/artifactory/package-info.java
- src/test/java/com/artipie/api/artifactory/CreateRepoSliceTest.java
- src/test/java/com/artipie/api/artifactory/package-info.java
Part of #413: added create repo api slice, implemented json body parsing and validation.
> Accept Artifactory create-repo API requests

- src/main/java/com/artipie/api/ArtipieApi.java
- src/main/java/com/artipie/api/artifactory/CreateRepoSlice.java
- src/test/java/com/artipie/api/artifactory/CreateRepoSliceTest.java
For #413 
- added regexp to handle with/without username requests to support both configuration layouts
- implemented saving yaml to storage
- added new endpoint for `CreateRepoSlice`
> #413 - create yaml config on create repo request

- src/main/java/com/artipie/http/TimeoutSlice.java
#423 - ignore `100` response statuses when marking response as finished in `TimeoutSlice`
> Fixed timeout slice with 100 status responses

- pom.xml
Updated http to `0.15.5`, asto to `0.23.4` and pypi to `0.6.1`.
> Updated http, asto and pypi

- pom.xml
- src/main/java/com/artipie/SliceFromConfig.java
- src/main/java/com/artipie/docker/DockerProxy.java
- src/test/java/com/artipie/docker/DockerProxyTest.java
Part of #401 
Upgraded Docker 4.0.2 that is using abstract HTTP client and does not leak proxy connections.
> #401 - Docker upgraded to 4.0.2

- pom.xml
- src/main/java/com/artipie/HttpClientSettings.java
For #451 
HTTP client upgraded to `0.2`, timeouts enabled
> #451 - HTTP client upgraded to 0.2, timeouts enabled

- src/main/java/com/artipie/http/HealthSlice.java
- src/main/java/com/artipie/http/Pie.java
- src/test/java/com/artipie/http/HealthSliceTest.java
#392 - added health endpoint for primary storage, it returns `OK` status if check passed and `BAD_REQUEST` (it seems to be the standard error for health check errors), and JSON array response with verbose statuses for each check (only storage for now).
> Added health endpoint

- src/main/java/com/artipie/ResponseMetricsSlice.java
Closes #292 
Replace ad-hoc with `error()`.
> #292 - remove ad-hoc

- src/main/java/com/artipie/RepoPermissions.java
- src/test/java/com/artipie/RepoPermissionsFromSettingsTest.java
Part of #494 and #497 
Artifactory method `PUT /api/security/permissions/{target}` request body json contains users and permissions in the following [format](https://www.jfrog.com/confluence/display/JFROG/Security+Configuration+JSON)
```
...
"users" : {
"bob": ["read","write","manage"],
"alice" : ["write","annotate", "read"]
}
...
```
So, I've
- introduced `UserPermission` class and changed `RepoPermissions#addUpdate` and `RepoPermissions#permissions` signature
- implemented and tested `RepoPermissions#addUpdate`
- implemented `RepoPermissions#remove` as it's part of `RepoPermissions#addUpdate`
> #494 - RepoPermissions.FromSettings fully implemented

- src/test/java/com/artipie/docker/DockerLocalIT.java
Closes #493 
Enabled Docker local tests on Windows. Corrected test class description.
> #493 - Enabled Docker local tests on Windows

- src/test/java/com/artipie/docker/DockerLocalAuthIT.java
Closes #499 
Added test cases for Docker repository when auth is required.
Th tests are disabled, because feature does not work at the moment. See #521
> #499 - Added Docker local repository auth tests

- benchmarks/0.10/benchmark-results.json
- benchmarks/0.9.1/benchmark-results.json
- benchmarks/0.9.2/benchmark-results.json
- benchmarks/0.9.3/benchmark-results.json
- benchmarks/0.9.5/benchmark-results.json
Remove old and publish new benchmarks results for Artipie versions `0.10 0.9.5 0.9.3 0.9.2 0.9.1`
Related #431.
> Publish benchmarks results 

- src/main/java/com/artipie/api/artifactory/GetStorageSlice.java
- src/main/java/com/artipie/api/artifactory/KeyList.java
- src/test/java/com/artipie/api/artifactory/KeyListTest.java
#545 - initial commit for Artifactory storage list API: added storage key formatting for JSON and other, added primitive `Slice` implementation.
> STtorage key list formatting and Artifactory storage API

- ARTIFACTORY_API_SUPPORT.md
- src/main/java/com/artipie/api/artifactory/AddUpdateUserSlice.java
- src/main/java/com/artipie/api/artifactory/DeleteUserSlice.java
- src/test/java/com/artipie/api/artifactory/AddUpdateUserSliceTest.java
- src/test/java/com/artipie/api/artifactory/DeleteUserSliceTest.java
Part of #555.
I've fully described user CRUD API and fixed 2 slices to correspond Artifactory API:
- made `DeleteUserSlice` return `User '{userName}' has been removed successfully.` 
- made `AddUpdateUserSlice` return bad request when invalid json was sent
> #555 - user CRUD API fully described

- src/main/java/com/artipie/api/artifactory/AddUpdatePermissionSlice.java
- src/main/java/com/artipie/api/artifactory/DeletePermissionSlice.java
- src/main/java/com/artipie/api/artifactory/GetPermissionSlice.java
- src/test/java/com/artipie/api/artifactory/DeletePermissionSliceTest.java
- src/test/java/com/artipie/api/artifactory/GetPermissionSliceTest.java
Closes #565 
Fixed `DeletePermissionSlice` and `GetPermissionSlice` to return 404 if repository does not exist.
> #565 - Artifactory API corrections

- src/main/java/com/artipie/api/artifactory/GetStorageSlice.java
- src/main/java/com/artipie/api/artifactory/KeyList.java
- src/test/java/com/artipie/api/artifactory/KeyListTest.java
Part of #548 
Storage list slice gives only immediate children of root node
> #548 - Storage list slice gives only immediate children of root node

- src/main/java/com/artipie/api/artifactory/AddUpdatePermissionSlice.java
- src/test/java/com/artipie/api/artifactory/AddUpdatePermissionSliceTest.java
Part of #574 
I've added permissions mapping to `AddUpdatePermissionSlice` before saving them to repo config, possible permissions values are from [this](https://www.jfrog.com/confluence/display/JFROG/Security+Configuration+JSON#SecurityConfigurationJSON-application/vnd.org.jfrog.artifactory.security.PermissionTargetV2+json) docs.
Note that
- `annotate`, `managedXrayMeta` and `distribute` are not included as we do not know what they mean and how to translate them
- `admin` and `manage` are translated to `*` which means any actions will be allowed to these users
I'm planning to document it when we discuss, possibly change something and merge this PR.
> #574 - permissions mapping in AddUpdatePermissionSlice

- REST_API.md
- src/main/java/com/artipie/api/artifactory/GetPermissionSlice.java
- src/test/java/com/artipie/api/artifactory/GetPermissionSliceTest.java
Closes #574 
I've changed `GetPermissionSlice` to shorten permissions actions and corrected docs.
> #574 - `GetPermissionSlice` and docs corrected

- pom.xml
- src/main/java/com/artipie/auth/AuthFromEnv.java
- src/main/java/com/artipie/auth/AuthFromYaml.java
- src/main/java/com/artipie/auth/CachedAuth.java
- src/main/java/com/artipie/auth/GithubAuth.java
- src/main/java/com/artipie/auth/LoggingAuth.java
- src/test/java/com/artipie/auth/AuthFromYamlTest.java
- src/test/java/com/artipie/auth/CachedAuthTest.java
- src/test/java/com/artipie/auth/GithubAuthTest.java
Part of #572 
Updated `http` and corrected `AuthFromYaml` read groups from `credentials.yaml`
> #572 - read groups in AuthFromYaml

- src/main/java/com/artipie/Settings.java
- src/main/java/com/artipie/Users.java
- src/main/java/com/artipie/YamlSettings.java
- src/main/java/com/artipie/api/ApiChangeUserPassword.java
- src/main/java/com/artipie/api/artifactory/AddUpdateUserSlice.java
- src/main/java/com/artipie/api/artifactory/DeleteUserSlice.java
- src/main/java/com/artipie/api/artifactory/GetUserSlice.java
- src/main/java/com/artipie/api/artifactory/GetUsersSlice.java
- src/test/java/com/artipie/UsersFromEnvTest.java
- src/test/java/com/artipie/UsersFromStorageYamlTest.java
- src/test/java/com/artipie/YamlSettingsTest.java
- src/test/java/com/artipie/api/ApiChangeUserPasswordTest.java
- src/test/java/com/artipie/api/artifactory/AddUpdateUserSliceTest.java
- src/test/java/com/artipie/api/artifactory/DeleteUserSliceTest.java
- src/test/java/com/artipie/api/artifactory/GetPermissionsSliceTest.java
- src/test/java/com/artipie/api/artifactory/GetUserSliceTest.java
- src/test/java/com/artipie/api/artifactory/GetUsersSliceTest.java
- src/test/java/com/artipie/http/DockerRoutingSliceTest.java
Part of #572 
Renamed `Credenctials` to `Users` which seem much more appropriate and implemented read/write user groups operation.
> #572 - read/write groups in Users.FromStorageYaml

- src/main/java/com/artipie/VertxMain.java
- src/main/java/com/artipie/http/AllRepositoriesSlice.java
- src/main/java/com/artipie/http/BaseSlice.java
- src/main/java/com/artipie/http/MainSlice.java
- src/test/java/com/artipie/AllRepositoriesSliceTest.java
Part of #570 
Extracted `BaseSlice`, `MainSlice` and `AllRepositoriesSlice`.
`BaseSlice` is expected to be used for running repository slice on separate port later.
> #570 - Extracted BaseSlice, MainSlice and AllRepositoriesSlice

- src/main/java/com/artipie/RepoPermissions.java
- src/main/java/com/artipie/api/artifactory/AddUpdatePermissionSlice.java
- src/main/java/com/artipie/api/artifactory/AddUpdateUserSlice.java
- src/main/java/com/artipie/api/artifactory/GetPermissionSlice.java
- src/test/java/com/artipie/RepoPermissionsFromSettingsTest.java
- src/test/java/com/artipie/RepoPerms.java
- src/test/java/com/artipie/api/artifactory/AddUpdatePermissionSliceTest.java
- src/test/java/com/artipie/api/artifactory/AddUpdateUserSliceTest.java
- src/test/java/com/artipie/api/artifactory/DeletePermissionSliceTest.java
- src/test/java/com/artipie/api/artifactory/GetPermissionSliceTest.java
Part of #573 
- user created from `AddUpdateUserSlice` always is in `readers` group
- repo permissions updated/created from `AddUpdatePermissionSlice` always include `read` right for `readers` groups
> #572 - add reader group and permission

- REST_API.md
- examples/npm/configs/npm_repo.yaml
- pom.xml
- src/main/java/com/artipie/SliceFromConfig.java
Part #572 
Updated adapters and docs, faced the following issues:
- could not update `npm-adapter` to `0.7` due to 
> [ERROR] Failed to execute goal on project artipie: Could not resolve dependencies for project com.artipie:artipie:jar:1.0-SNAPSHOT: Failed to collect dependencies at com.artipie:npm-adapter:jar:0.7: Failed to read artifact descriptor for com.artipie:npm-adapter:jar:0.7: Could not transfer artifact com.artipie:npm-adapters:pom:0.7 from/to artipie-central (https://central.artipie.com/artipie/maven): Failed to transfer file: https://central.artipie.com/artipie/maven/com/artipie/npm-adapters/0.7/npm-adapters-0.7.pom. Return code is: 502 , ReasonPhrase:Bad Gateway. -> [Help 1]
(force update of the local repository did not help)
- composer-adapter is not yes released
- …
> #572 - Update adapters and docs

- README.md
Closes #573 
I've documented assigning groups for users in `credentials.yaml`. 
**Suggestion**: now we do not have description for `permissions` section in repository config. I'd suggest to add this information to examples readme and also move section about port setting from the main readme to the examples readme.
> #573 - Document user groups

- README.md
Part of #647 
Added TOC and documented repo permissions. You can check md [here](https://github.com/olenagerasimova/artipie/tree/647-repo-perms)
> #647 - document repo perms

- src/main/java/com/artipie/RepoPermissions.java
- src/test/java/com/artipie/RepoConfigYaml.java
- src/test/java/com/artipie/RepoPerms.java
- src/test/java/com/artipie/api/artifactory/GetStorageSliceTest.java
- src/test/java/com/artipie/auth/AuthAndPermissionsTest.java
- src/test/java/com/artipie/docker/DockerOnPortIT.java
- src/test/java/com/artipie/docker/DockerProxyIT.java
- src/test/java/com/artipie/nuget/NugetITCase.java
Part of #660 
Extended `RepoConfigYaml` and used it in various test classes to create repo config. 
Decided to leave `DockerProxyTest` as is as (its config is large and such configuration is used only once).
> #660 - used RepoConfigYaml in various tests

- src/test/java/com/artipie/RepoPerms.java
- src/test/java/com/artipie/api/artifactory/AddUpdatePermissionSliceTest.java
- src/test/java/com/artipie/api/artifactory/GetPermissionSliceTest.java
Closes #660 
Used `RepoConfigYaml.saveTo` instead of `RepoPerms.saveSettings` and removed not needed any more methods.
> #660 - use RepoConfigYaml instead of RepoPerms

- .github/workflows/integration-tests.yml
- pom.xml
Closes #680 
I've extracted IT into separate profile and added separate action for them. 
Now to run ITs it's necessary to explicitly turn on `itcase` profile by adding `-Pitcase` option:
```
mvn clean install -Pitcase
```
> #680 - separate profile for IT

- pom.xml
- src/main/java/com/artipie/maven/MavenProxy.java
Closes #674
Using `GenericAuthenticator` in `MavenProxy`
> #674 - Using GenericAuthenticator in MavenProxy

- src/main/java/com/artipie/http/SliceByPath.java
- src/test/java/com/artipie/AllRepositoriesSliceTest.java
Closes #633 
Respond with 404 to request not related to repositories in `SliceByPath`
> #633 - Response 404 to request not related to repos

- src/main/java/com/artipie/maven/MavenProxy.java
- src/main/resources/dashboard/repo.hbs
- src/main/resources/example/repo/test/maven-proxy.yaml
- src/test/java/com/artipie/RepoConfigYaml.java
- src/test/java/com/artipie/maven/MavenProxyAuthIT.java
- src/test/java/com/artipie/maven/MavenProxyIT.java
Part of #608 
Using `RepoConfig` in `MavenProxy`. Format for `maven-proxy` repository changed
> #608 - Using RepoConfig in MavenProxy

- src/test/java/com/artipie/CredsConfigYaml.java
- src/test/java/com/artipie/api/ApiChangeUserPasswordTest.java
- src/test/java/com/artipie/auth/AuthAndPermissionsTest.java
- src/test/java/com/artipie/auth/AuthFromYamlTest.java
Part of #690 
In #203 we introduced config format with separate yaml field for password type: 
```
username:
type: plain/sha256
pass: 123
...
``` 
Such format seems more readable, that's why I've corrected `CredsConfigYaml` to use separate field for type and left old format only in `AuthFromYamlTest` to verify it's working. Also added several methods to `CredsConfigYaml` and used it tests.
> #690 - use CredsConfigYaml

- README.md
- src/main/java/com/artipie/Users.java
- src/test/java/com/artipie/ArtipieServer.java
- src/test/java/com/artipie/CredsConfigYaml.java
- src/test/java/com/artipie/UsersFromStorageYamlTest.java
- src/test/java/com/artipie/api/ApiChangeUserPasswordTest.java
- src/test/java/com/artipie/api/artifactory/AddUpdateUserSliceTest.java
Closes #690 
Corrected `Users.FromStorageYaml` to save password with format in separate field and used `CredsConfigYaml` in the corresponding test. Also, corrected and extended readme
> #690 - use CredsConfigYaml, correct Users.FromStorageYaml and readme

- pom.xml
- src/main/java/com/artipie/SliceFromConfig.java
- src/main/java/com/artipie/api/ArtipieApi.java
- src/main/java/com/artipie/api/AuthApi.java
- src/main/java/com/artipie/dashboard/DashboardSlice.java
- src/main/java/com/artipie/http/DockerRoutingSlice.java
- src/test/java/com/artipie/auth/AuthAndPermissionsTest.java
Part of #693
Docker upgraded to 0.4.8 and HTTP to 0.16.5
In many places deprecation warning were suppressed. Should be fixed later
> #693 - Docker upgraded to 0.4.8

- src/test/java/com/artipie/file/FileProxyAuthIT.java
- src/test/java/com/artipie/file/FilesRepoITCase.java
- src/test/java/com/artipie/maven/MavenITCase.java
- src/test/java/com/artipie/maven/MavenMultiProxyIT.java
- src/test/java/com/artipie/maven/MavenProxyAuthIT.java
- src/test/java/com/artipie/maven/MavenProxyIT.java
- src/test/java/com/artipie/npm/NpmITCase.java
- src/test/java/com/artipie/nuget/NugetITCase.java
- src/test/java/com/artipie/pypi/PypiITCase.java
- src/test/java/com/artipie/pypi/PypiProxyITCase.java
- src/test/java/com/artipie/rpm/RpmITCase.java
- src/test/java/com/artipie/test/TestContainer.java
- src/test/java/com/artipie/test/package-info.java
Part of #722
Extract to a separate class creating a test container. Also use path `tmp` instead of `subir` in `MavenITCase`.
> #722 - Create a separate class for test container

- src/test/java/com/artipie/npm/NpmITCase.java
- src/test/java/com/artipie/pypi/PypiITCase.java
- src/test/java/com/artipie/pypi/PypiProxyITCase.java
- src/test/java/com/artipie/rpm/RpmITCase.java
- src/test/java/com/artipie/test/RepositoryUrl.java
- src/test/java/com/artipie/test/UrlCredsHelper.java
Closes #722 
Add `UrlCredsHelper` to simplify working with url that may contains user credentials.
> #722 - Add UrlHelper for url with user credentials

- src/main/java/com/artipie/VertxMain.java
- src/main/java/com/artipie/YamlSettings.java
- src/test/java/com/artipie/YamlSettingsTest.java
Part of #729 
I've changed field in `YamlSettings` from `String` to `YamlMapping` and removed exceptions from methods signatures.
> #729 - yaml mapping instead of string field in YamlSettings

- src/main/java/com/artipie/RepoPermissions.java
- src/main/java/com/artipie/api/ArtipieApi.java
- src/main/java/com/artipie/api/artifactory/AddUpdatePermissionSlice.java
- src/main/java/com/artipie/api/artifactory/DeletePermissionSlice.java
- src/main/java/com/artipie/api/artifactory/GetPermissionSlice.java
- src/main/java/com/artipie/api/artifactory/GetPermissionsSlice.java
- src/test/java/com/artipie/RepoPermissionsFromSettingsTest.java
- src/test/java/com/artipie/api/artifactory/AddUpdatePermissionSliceTest.java
- src/test/java/com/artipie/api/artifactory/DeletePermissionSliceTest.java
- src/test/java/com/artipie/api/artifactory/GetPermissionSliceTest.java
- src/test/java/com/artipie/api/artifactory/GetPermissionsSliceTest.java
Part of #730 
Changed `RepoPermissions` implementation signature and corresponding API slices.
> #730 - RepoPermissions signature changed

- src/main/java/com/artipie/SliceFromConfig.java
- src/main/java/com/artipie/api/ArtipieApi.java
- src/main/java/com/artipie/api/artifactory/AddUpdatePermissionSlice.java
- src/main/java/com/artipie/api/artifactory/CreateRepoSlice.java
- src/main/java/com/artipie/api/artifactory/DeletePermissionSlice.java
- src/main/java/com/artipie/api/artifactory/GetStorageSlice.java
- src/main/java/com/artipie/repo/PathPattern.java
- src/test/java/com/artipie/api/artifactory/CreateRepoSliceTest.java
- src/test/java/com/artipie/api/artifactory/GetStorageSliceRequestTest.java
- src/test/java/com/artipie/api/artifactory/GetStorageSliceTest.java
Part of #730 
Changed `PathPattern` to accept `layout` instead of `settings` and made `CreateRepoSlice` and `GetStorageSlice` do not depend on `settings`.
> #730 - storage and repo API

- pom.xml
- src/main/java/com/artipie/SliceFromConfig.java
- src/main/java/com/artipie/docker/DockerProxy.java
Closes #755 
`docker-adapter` upgraded to 0.6
> #755 - docker-adapter upgraded to 0.6

- pom.xml
- src/test/java/com/artipie/nuget/NugetITCase.java
Closes #679 
NuGet upgraded to `0.4`, tests enabled
> #679 - NuGet upgraded to 0.4, tests enabled

- src/test/java/com/artipie/gem/GemITCase.java
Closes #606 
Add authentication push and install IT for Gem. Now these test cases are disabled. Add todo to enable them after passing of authentication and permissions would be implemented.
> #606 - Add authentication push and install IT for Gem

- pom.xml
- src/test/java/com/artipie/gem/GemITCase.java
Part of #768 
Updated version of gem-adapter and http module. Enabled test for this feature.
> #768 - Support Basic auth for Gem

- src/main/java/com/artipie/RepositoriesFromStorage.java
- src/main/java/com/artipie/StorageAliases.java
- src/main/java/com/artipie/VertxMain.java
- src/test/java/com/artipie/RepositoriesFromStorageTest.java
Closes #786 
Added negative tests to `RepositoriesFromStorage`. Fixed `StorageAliases.FromYaml`  implementation for the cases when yaml is malformed or alias name is absent.
> #597 - Add negative tests to RepositoriesFromStorage

- src/main/java/com/artipie/SliceFromConfig.java
- src/test/java/com/artipie/npm/NpmProxyITCase.java
Closes #738 
The problem was that the `TrimPathSlice` cut off repository name from the request therefore patterns that were created before in `NpmProxySlice` became invalid. Refusing to use `trimIfNotStandalone` in `SliceFromConfig` for `npm-proxy` helped to solve this problem.
> #738 - Fix path handling for NpmProxySlice

- src/main/java/com/artipie/RepoPermissionsFromStorage.java
- src/main/java/com/artipie/RepositoriesFromStorage.java
- src/main/java/com/artipie/StorageAliases.java
- src/main/java/com/artipie/repo/ConfigFile.java
- src/test/java/com/artipie/RepoConfigYaml.java
- src/test/java/com/artipie/RepoPermissionsFromSettingsTest.java
- src/test/java/com/artipie/RepositoriesFromStorageTest.java
- src/test/java/com/artipie/repo/ConfigFileTest.java
Part of #797 
Implemented `valueFrom` to get content from file with either of two extensions (`yaml` and `yml`). Added tests.
> #797 - Get value for different extensions 

- src/main/java/com/artipie/api/ArtipieApi.java
- src/main/java/com/artipie/api/DashboardSlice.java
- src/test/java/com/artipie/api/ArtipieApiITCase.java
Closes #797 
Support both extensions `.yaml` and `.yml` for `ArtipieApi` and `DashboardSlice`.
> #797 - Support both extensions for ArtipieApi and DashboardSlice

- pom.xml
- src/main/java/com/artipie/SliceFromConfig.java
- src/main/java/com/artipie/docker/DockerProxy.java
Closes #820 
`docker-adapter` upgraded to `0.9.3`
> #820 - docker-adapter upgraded to 0.9.3

- src/test/java/com/artipie/helm/HelmITCase.java
Closes #822 
The problem is related to the fact that https://kubernetes-charts.storage.googleapis.com/index.yaml as default stable repository is no longer allowed (https://stackoverflow.com/a/65404574/14676855).
Fix this problem by adding local repository which contains `index.yaml` file.
> #822 - Fix HelmIT

- pom.xml
Closes #829 
`docker-adapter` upgraded to `0.10`
> #829 - docker-adapter upgraded to 0.10

- examples/npm/run.sh
- examples/utils.sh
#847 - added common bash utils for all examples, refactored npm to use it, added `trap` to stop artipie container in any case
> Examples scripts

- .github/workflows/release.yml
Fixes #655 - create GitHub release based on tag
after deploying Docker image to DockerHub.
Release is not a draft or pre-release, it contains
tag annotation message as body.
> Creating GitHub release after deploy to registry

- src/test/java/com/artipie/debian/DebianGpgITCase.java
- src/test/java/com/artipie/debian/DebianITCase.java
- src/test/java/com/artipie/file/FileITCase.java
- src/test/java/com/artipie/file/FileProxyAuthIT.java
- src/test/java/com/artipie/gem/GemITCase.java
- src/test/java/com/artipie/maven/MavenITCase.java
- src/test/java/com/artipie/maven/MavenProxyAuthIT.java
- src/test/java/com/artipie/maven/MavenProxyIT.java
- src/test/java/com/artipie/npm/NpmITCase.java
- src/test/java/com/artipie/npm/NpmProxyITCase.java
- src/test/java/com/artipie/nuget/NugetITCase.java
- src/test/java/com/artipie/pypi/PypiProxyITCase.java
- src/test/java/com/artipie/rpm/RpmITCase.java
- src/test/java/com/artipie/test/ContainerResultMatcher.java
Closes #862 
Moved `ContainerResultMatcher` to a separate file, added several ctors and constant for success status.
> Moved `ContainerResultMatcher` to a separate file

- pom.xml
- src/main/java/com/artipie/SliceFromConfig.java
- src/main/java/com/artipie/php/ComposerProxy.java
- src/main/java/com/artipie/php/package-info.java
Closes #895 
Bumped composer adapter to `1.0` to use added functionality. Added composer proxy type of repository
Bumped management-api to `0.4.5` to show absent types of repository in dropdown list
> Bump composer-adapter and management-api, add composer proxy

- src/main/java/com/artipie/ArtipieProperties.java
- src/main/java/com/artipie/RepoConfig.java
- src/main/java/com/artipie/RepositoriesFromStorage.java
- src/main/resources/artipie.properties
- src/test/java/com/artipie/RepositoriesFromStorageCacheTest.java
- src/test/java/com/artipie/RepositoriesFromStorageTest.java
- src/test/resources/_storages.yaml
Closes #195 
Added cache with soft references with eviction which is equal to two minutes for repository configuration files and for aliases with configs of storage.
> Added cache for configuration files

- src/main/java/com/artipie/ArtipieProperties.java
- src/main/java/com/artipie/RepositoriesFromStorage.java
- src/main/java/com/artipie/VertxMain.java
- src/main/java/com/artipie/YamlSettings.java
- src/main/java/com/artipie/auth/AuthCache.java
- src/main/java/com/artipie/auth/CachedAuth.java
- src/main/java/com/artipie/auth/CachedUsers.java
- src/main/resources/artipie.properties
- src/test/java/com/artipie/YamlSettingsTest.java
- src/test/java/com/artipie/auth/CachedAuthTest.java
- src/test/java/com/artipie/auth/CachedUsersTest.java
Closes #339 #460 
Specify expiration time for auth, used guava implementation.
Extracted `AuthCache` interface for creating instance of `CachedAuth` only once. Created `CachedAuthWrap` for using passed instance of `AuthCache` in `YamlSettings#auth` .
> Specify expiration time and refactor `CachedAuth`

- src/test/java/com/artipie/YamlSettingsTest.java
Closes #299 
Added test which verifies that user is authenticated when `credentials` section is absent
> Add test for authentication without credentials section

- src/test/java/com/artipie/ArtipieServer.java
Closes #470 
I do not think refactoring from this `todo` is actually required: as there are basically only two places in test code where `artipie.yaml` is created - `ArtipieServer` and test for settings `YamlSettingsTest`. `YamlSettingsTest` has a lot of different variants of artipie.yaml (to test that in all cases settings are read correctly) and for test it's ok (and even better in my opinion) to have all these variants as string stabs.
> Removed not actual @todo

- pom.xml
- src/test/java/com/artipie/helm/HelmITCase.java
Run https://github.com/gaul/modernizer-maven-plugin
on `verify` phase to detect legacy API usages in code.
Fixed `HelmITCase` issue reported by plugin.
@artipie/members you may want to add this plugin to other modules too, see plugin readme for details.
> ci: added modernizer plugin into verify pipeline

- src/main/java/com/artipie/docker/DockerProxy.java
- src/main/java/com/artipie/maven/MavenProxy.java
- src/main/java/com/artipie/php/ComposerProxy.java
- src/main/java/com/artipie/pypi/PypiProxy.java
- src/main/java/com/artipie/repo/CacheStorage.java
- src/main/java/com/artipie/repo/ProxyConfig.java
- src/main/java/com/artipie/repo/YamlCacheStorage.java
- src/main/java/com/artipie/repo/YamlProxyConfig.java
Part of #334 
Added interface for obtaining TTL and max size values from config of repo. In next PR, I'm planning to add some tests
> feat: add TTL and max size for cache storages in proxy repos

- .github/workflows/ci-checks.yml
- .github/workflows/integration-tests.yml
- .github/workflows/reports.yml
- Dockerfile
- pom.xml
- src/test/java/com/artipie/VertxMainITCase.java
- src/test/java/com/artipie/docker/DockerOnPortIT.java
- src/test/java/com/artipie/docker/DockerProxyIT.java
- src/test/java/com/artipie/helm/HelmITCase.java
- src/test/java/com/artipie/maven/MavenMultiProxyIT.java
Change source and target version to 17 in `pom.xml`.
Configured `Dockerfile` to use oracle-17 JDK.
Enabled CI builds for 17 JDK.
> env: switch to oracle-17 jdk

- .github/workflows/ci-checks.yml
- pom.xml
- src/test/java/com/artipie/helm/HelmITCase.java
Updated qulice to `0.19.0` with fix yegor256/qulice#1095
Enabled it in CI pipeline.
> ci: bump qulice and enabled for CI pipeline

- src/main/java/com/artipie/CachedStorages.java
- src/main/java/com/artipie/SettingsCaches.java
- src/main/java/com/artipie/SettingsFromPath.java
- src/main/java/com/artipie/StorageConfigCache.java
- src/main/java/com/artipie/YamlSettings.java
- src/test/java/com/artipie/CachedStoragesTest.java
- src/test/java/com/artipie/YamlSettingsTest.java
Part of #87 
Used `CachedStorages` in `YamlSettings`.
I am not sure about passing `Settings` to `CachedStorages#storage(Settings)` because in `Settings` `CachedStorages` is used. Probably it would be better to pass `YamlMapping` because it is necessary to use only one section from the whole setting but in this case we would depend more on yaml format
> feat: use `CachedStorages`

- src/main/java/com/artipie/UsersFromStorageYaml.java
- src/main/java/com/artipie/YamlSettings.java
- src/main/java/com/artipie/cache/CachedCreds.java
- src/main/java/com/artipie/cache/CredsConfigCache.java
- src/main/java/com/artipie/cache/SettingsCaches.java
- src/main/java/com/artipie/misc/ArtipieProperties.java
- src/main/resources/artipie.properties
- src/test/java/com/artipie/UsersFromStorageYamlTest.java
- src/test/java/com/artipie/YamlSettingsTest.java
- src/test/java/com/artipie/cache/CachedCredsTest.java
Part of #87 
Added cache for credentials configuration. At first, it reads credentials section from Artipie settings. If this content exists in cache and is not expired, credentials will be loaded from the cache. Otherwise a new instance will be created. Next I'm planning to add more tests
> feat: add cache for credentials configuration

- src/main/java/com/artipie/cache/CachedStorages.java
- src/main/java/com/artipie/cache/CachedUsers.java
- src/test/java/com/artipie/cache/CachedCredsTest.java
- src/test/java/com/artipie/cache/CachedStoragesTest.java
- src/test/java/com/artipie/cache/CachedUsersTest.java
Closes #87
Used instance field instead of static because this instance is created only once. I didn't refactor static field in `RepositoriesFromStorage` because instances of this class are created many times
> refactor: use instance field for cache

- src/main/resources/log4j.properties
- src/test/resources/log4j.properties
Log4j got zero-day vulnerability, which could be mitigated by configuration changes in the commit. More details could be found below:
https://securityonline.info/apache-log4j2-remote-code-execution-vulnerability-alert/
> Avoiding log4j vulnerability CVE-2021-44228

- pom.xml
- src/main/java/com/artipie/http/PromuSlice.java
- src/main/java/com/artipie/metrics/memory/InMemoryMetrics.java
- src/main/java/com/artipie/metrics/publish/PrometheusOutput.java
- src/test/java/com/artipie/http/PromuSliceTest.java
- Introduce tests that check that `PromuSlice` not only produces metrics in the right format according to accepted mime type but also returns only metrics that match to specified names as filters.
- Add a todo for integration testing about availability of `PromuSlice` when we set up `Prometheus` in `meta` configuration.
Close: #978
> test: cover PromuSlice

- src/main/java/com/artipie/SliceFromConfig.java
Closes #110 
Removed not relevant pdd puzzle: we already check repository type in switch block and throw exception if repository type is not valid.
> Removed not relevant pdd puzzle

- .github/workflows/integration-tests.yml
- .github/workflows/release.yml
- src/main/java/com/artipie/RepoConfig.java
- src/test/java/com/artipie/VertxMainITCase.java
- src/test/java/com/artipie/rpm/RpmITCase.java
- src/test/resources/artipie-repo-config-key.yaml
- src/test/resources/invalid_repo.yaml
We migrate `VertxMainITCase` to testcontainers and we fix test `startsWhenNotValidRepoConfigsArePresent` that was failing.
We add a puzzle to fix other test case.
Fix: #977
> test: fix VertxMainITCase

- .pdd
We noticed that sometimes we can use the keyword `@todo` in `CHANGELOG.md`, `CODE_OF_CONDUCT.md`, `CONTRIBUTING.md` without it being a puzzle. But `pdd` will fail on that saying that it doesn't match to puzzle format.
We decided to exclude them all from pdd checking.
Cc: [commit-b281fbd9](https://github.com/artipie/artipie/commit/b281fbd957752567387e707f090cfd5b52fc931a#commitcomment-65919004)
> fix(pdd): exclude some doc files

- .github/workflows/ci-checks.yml
- pom.xml
- src/main/java/com/artipie/http/PromuSlice.java
A new method has been introduced in `RqParams` (artipie/http) that allow us to obtain all values of a
query parameter. We refactored `PromuSlice` with this new method.
Ref: #978
> refactor: replace params method in PromuSlice

- src/main/java/com/artipie/UsersFromGithub.java
- src/main/java/com/artipie/YamlSettings.java
- src/main/resources/example/artipie.yaml
- src/test/java/com/artipie/YamlSettingsTest.java
Closes #337 
- added an opportunity to set Github auth in YAML settings
- added an opportunity to set a few authentications in YAML settings
```
credentials:
-
type: file
path: _credentials.yaml
-
type: env
```
If there is only one type of credentials, then it can be set up as before
```
credentials:
type: file
path: _credentials.yaml
```
- added tests to check Github auth and alternative authentication
> feat: alternative authentication

- src/main/java/com/artipie/auth/GithubAuth.java
- src/test/java/com/artipie/auth/GithubAuthTest.java
Closes #406 
- added auth error handling to `GithubAuth`
- added tests for cases when auth is failed and any other error happens
> fix: GithubAuth should return empty Optional when authentication is failed

- src/test/java/com/artipie/rpm/RpmITCase.java
Closes #993 
Sentos 8 went EOL in December 2021, so I've corrected the test to use fedora 35 and dnf.
> fix: corrected RpmITCase to use fedora instead of sentos 8

- src/main/java/com/artipie/ResponseMetricsSlice.java
- src/test/java/com/artipie/ResponseMetricsSliceTest.java
We catch exceptions and send them to metrics.
Fix: #273
> fix: report exceptions as error in ResponseMetricsSlice

- .github/workflows/integration-tests.yml
- src/test/java/com/artipie/docker/DockerOnPortIT.java
- src/test/java/com/artipie/test/TestDeployment.java
Closes #1005 
Closes #1009 
- added overridden methods to `com.artipie.test.TestDeployment.ArtipieContainer` that let to specify a config as a string
- test `DockerOnPortIT` migrated to testcontainres
> test: `DockerOnPortIT` migrated to testcontainres; testcontainres config as string

- .wiki/Configuration.md
Closes #999 
- added description of the `env` credentials type
- added description of the `github` credentials type
- added  description of alternative authentication
> docs: added to the Configuration.md about several auth

- pom.xml
This version fixes conda smoke test.
Ref: #995
> deps: bump `conda-adapter` from `v0.5.2` to `v0.5.3`

- README.md
- docker-compose.yaml
- src/main/resources/example/artipie.yaml
- src/main/resources/example/repo/_storages.yaml
Closes #1028 
Added docker-compose script to run both Artipie and Artipie front, corrected readme. 
Note, that I'm not a devops and have no idea about best practicies for such type of configurations.
> feat: add docker-compose.yaml and correct README.md

- Dockerfile
- src/main/java/com/artipie/SliceFromConfig.java
- src/main/java/com/artipie/VertxMain.java
- src/main/java/com/artipie/http/ArtipieRepositories.java
- src/main/java/com/artipie/http/SliceByPath.java
- src/test/java/com/artipie/composer/PhpComposerITCase.java
- src/test/java/com/artipie/conda/CondaITCase.java
- src/test/java/com/artipie/debian/DebianITCase.java
- src/test/java/com/artipie/file/FileITCase.java
- src/test/java/com/artipie/file/FileProxyAuthIT.java
- src/test/java/com/artipie/gem/GemITCase.java
- src/test/java/com/artipie/helm/HelmITCase.java
- src/test/java/com/artipie/maven/MavenITCase.java
- src/test/java/com/artipie/maven/MavenMultiProxyIT.java
- src/test/java/com/artipie/maven/MavenProxyIT.java
- src/test/java/com/artipie/npm/NpmITCase.java
- src/test/java/com/artipie/npm/NpmProxyITCase.java
- src/test/java/com/artipie/nuget/NugetITCase.java
- src/test/java/com/artipie/pypi/PypiITCase.java
- src/test/java/com/artipie/rpm/RpmITCase.java
- src/test/resources/binary/bin-port.yml
- src/test/resources/binary/bin-proxy-port.yml
- src/test/resources/helloworld-src/pom-port.xml
- src/test/resources/maven/maven-port.yml
- src/test/resources/maven/maven-settings-port.xml
- src/test/resources/snapshot-src/pom-port.xml
Part of #1041 
Fixed cases with repository port:
1) path trimming is necessary when repo port is set (for now, I've only fixed it for files repository and added corresponding tests)
2) repository with port should not be accessible by default port
> fix: repository port usage

- .wiki/Configuration-Credentials.md
- .wiki/Configuration-Metrics.md
- .wiki/Configuration-Repository Permissions.md
- .wiki/Configuration-Repository.md
- .wiki/Configuration-Storage.md
- .wiki/Configuration.md
- README.md
Part of #1031 
Created wiki sections structure and moved all the information from readme there. In readme I've left only general description, quickstart section and contributing details. 
Then I will extend and reformat each wiki page one by one.
> doc: move all the configs details to wiki

- src/test/java/com/artipie/npm/NpmProxyITCase.java
- src/test/resources/npm/npm-proxy-port.yml
closes: #1055
Hi @olenagerasimova.
Could you please to take a look at this PR?
> fix: extended NpmProxyITCase to test individual repository port

- src/main/java/com/artipie/SliceFromConfig.java
- src/main/java/com/artipie/VertxMain.java
- src/main/java/com/artipie/adapters/docker/DockerProxy.java
- src/main/java/com/artipie/adapters/file/FileProxy.java
- src/main/java/com/artipie/adapters/maven/MavenProxy.java
- src/main/java/com/artipie/adapters/php/ComposerProxy.java
- src/main/java/com/artipie/adapters/pypi/PypiProxy.java
- src/main/java/com/artipie/http/ArtipieRepositories.java
- src/main/java/com/artipie/settings/RepositoriesFromStorage.java
- src/main/java/com/artipie/settings/repo/RepoConfig.java
- src/main/java/com/artipie/settings/repo/proxy/YamlProxyConfig.java
- src/test/java/com/artipie/docker/DockerProxyTest.java
- src/test/java/com/artipie/settings/RepositoriesFromStorageCacheTest.java
- src/test/java/com/artipie/settings/repo/RepoConfigTest.java
- src/test/java/com/artipie/settings/repo/RepositoriesFromStorageTest.java
Part of #1099 
I've simplified `RepoConfig` class by:
- moving static method `fromPublisher()` to `RepositoriesFromStorage` class
- removing and inlining method `proxy()`
> feat: simplify `RepoConfig` class

- .wiki/Configuration-Repository.md
- .wiki/_Sidebar.md
- README.md
Closes #1111 
- Removed word `experimental` from `readme` file.
- Added a link to the wiki doc before `Quickstart` section.
- Added a link to the list of adapters in the according wiki section.
> doc improvements

- src/test/java/com/artipie/api/RepositoryRestFlatTest.java
- src/test/java/com/artipie/api/RepositoryRestOrgTest.java
- src/test/java/com/artipie/api/RestApiServerBase.java
- src/test/java/com/artipie/api/StorageAliasesRestFlatTest.java
- src/test/java/com/artipie/api/StorageAliasesRestOrgTest.java
part of #1099 
I've simplified tests by extending `RestApiServerBase#requestAndAssert` method functionality and using it to avoid duplications.
> feat: simplify tests

- src/main/java/com/artipie/VertxMain.java
- src/main/java/com/artipie/api/RestApi.java
- src/main/java/com/artipie/api/UsersRest.java
- src/main/java/com/artipie/api/ValidRepositoryName.java
- src/main/java/com/artipie/settings/Settings.java
- src/main/java/com/artipie/settings/YamlSettings.java
- src/main/resources/example/artipie.yaml
- src/main/resources/swagger-ui/swagger-initializer-flat.js
- src/main/resources/swagger-ui/swagger-initializer-org.js
- src/main/resources/swagger-ui/yaml/users.yaml
- src/test/java/com/artipie/api/ManageUsersTest.java
- src/test/java/com/artipie/api/RestApiServerBase.java
- src/test/java/com/artipie/api/UsersRestTest.java
- src/test/java/com/artipie/http/DockerRoutingSliceTest.java
Part of #1099 
Added endpoint to get users list. 
As endpoint to manage users are the same for org and flat layouts, I've added new single open api yaml. In swagger, repositories and users APIs will be available by user's chose, check the screenshot:
> feat: added endpoint to get users list

- src/main/java/com/artipie/api/ManageUsers.java
- src/main/java/com/artipie/api/UsersRest.java
- src/main/java/com/artipie/settings/users/CrudUsers.java
- src/main/resources/swagger-ui/yaml/users.yaml
- src/test/java/com/artipie/api/ManageUsersTest.java
- src/test/java/com/artipie/api/UsersRestTest.java
Part of #1099 
Fixed `ManageUsers#list()` to remove user's password from user info, we should not return the password in rest api responses and added get method to obtain single user info.
> feat: get user info

- .wiki/repositories/anaconda.md
- .wiki/repositories/composer.md
- .wiki/repositories/debian.md
- .wiki/repositories/docker-proxy.md
- .wiki/repositories/docker.md
- .wiki/repositories/file.md
- .wiki/repositories/gem.md
- .wiki/repositories/go.md
- .wiki/repositories/helm.md
- .wiki/repositories/hexpm.md
- .wiki/repositories/npm-proxy.md
- .wiki/repositories/npm.md
- .wiki/repositories/pypi-proxy.md
- .wiki/repositories/pypi.md
- .wiki/repositories/rpm.md
close: #1138 
Remove .md extension in links
> fix: Broken links on wiki pages #1137

- src/main/java/com/artipie/VertxMain.java
- src/main/java/com/artipie/api/RestApi.java
Part of #1099 
Added a separate cmd parameter to specify port to start Artipie rest api on.
But in the case SSL is used, it seems we have to use port 443 and ignore this option...
> feat: rest api port parameter

- .wiki/Configuration-Repository.md
Removed `.md` extensions from repository types table as with this extension links do not work correctly.
> wiki: corrected repo table links

- .wiki/Configuration-Credentials.md
- .wiki/Configuration-Metrics.md
- .wiki/Configuration-Repository-Permissions.md
- .wiki/Configuration-Repository.md
- .wiki/Configuration.md
Fixing wiki links again: they should not have `.md` at the end. Also, in the repository types table they do work, trying different variants.
> wiki: fix links

- Dockerfile
I suggest adding optional `--jmx` flag for debug/test purposes. It will be disabled by default. Usage:
`docker run .... -p 8888:8888 artipie/artipie --jmx`
> Optional '--jmx' for debug/test purposes

- .github/workflows/integration-tests.yml
- pom.xml
- src/test/java/com/artipie/settings/YamlSettingsTest.java
- src/test/java/com/artipie/settings/YamlStorageTest.java
I've caught the following exception on Central:
```
java.util.concurrent.CompletionException: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/hamcrest/Matcher
java.util.concurrent.CompletionException: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/hamcrest/Matcher
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFu …
```
> fix: github auth is broken

- examples/artipie.yml
- examples/conda/run.sh
- pom.xml
- src/main/java/com/artipie/auth/AuthFromEnv.java
- src/test/java/com/artipie/conda/CondaITCase.java
- src/test/java/com/artipie/docker/DockerProxyIT.java
- src/test/java/com/artipie/settings/YamlSettingsTest.java
`AuthFromEnv` should return empty optional if it fails to authorize user and `hamcrest` is required in the main code for `jcabi-github` to work properly.
Had to correct several tests and add credentials settings for smoke tests: `conda` client does not work without users and authorization at all, before the fix, Artipie simply used this anonymous from `AuthFromEnv`, now it uses user from credentials as should.
> fix: AuthFromEnv corrected, hamcrest added to the main code

- src/main/java/com/artipie/settings/YamlSettings.java
- src/main/resources/example/artipie.yaml
While reviewing https://github.com/artipie/front/pull/106 I run to guava cache "Recursive load" error in the case of specific auth configuration. The error was caused by double caching of github auth, which should not be done. Removed extra caching and corresponding classes, now all the caching is implemented via `SettingsCaches.All` class.
> fix: use cached auth properly

- src/main/java/com/artipie/http/BaseSlice.java
- src/main/java/com/artipie/http/MainSlice.java
- src/main/java/com/artipie/http/PrometheusSlice.java
- src/main/java/com/artipie/metrics/Metrics.java
- src/main/java/com/artipie/metrics/MetricsFromConfig.java
- src/main/java/com/artipie/metrics/memory/InMemoryMetrics.java
- src/main/java/com/artipie/metrics/nop/NopMetrics.java
- src/main/java/com/artipie/metrics/publish/MetricsOutput.java
- src/test/java/com/artipie/PrometheusSliceITCase.java
- src/test/java/com/artipie/http/MainSliceTest.java
- src/test/java/com/artipie/http/PrometheusSliceTest.java
- src/test/resources/artipie-metrics-prometheus.yaml
Closes #1174
- Do not create metrics related slices when metrics are not defined
- Added exception when `NopMetrics` is used to publish metrics
- `PromuXXX` rename to `PrometheusXXX`
- `InMemoryMetrics` refactoring
> Do not create metrics related slices when metrics are not defined

- src/main/java/com/artipie/jfr/ChunksAndSizeMetricsContent.java
- src/main/java/com/artipie/jfr/ChunksAndSizeSubscriber.java
- src/main/java/com/artipie/jfr/package-info.java
- src/test/java/com/artipie/jfr/ChunksAndSizeMetricsContentTest.java
- src/test/java/com/artipie/jfr/package-info.java
part of #1183
implemented ChunksAndSizeMetricsContent allows getting chunks count and received data size.
tests to check ChunksAndSizeMetricsContent
> `Content` wrapper that allows to get chunks count and received data size

- README.md
fix: README.md contained a wrong link to codecov.io
Fix: #1211
> README.md contained a wrong link to codecov.io

- pom.xml
- src/test/java/com/artipie/HttpClientSettingsTest.java
- Removed dependency to powermock-api-mockito2 because it is not used anywhere.
- Removed the todo comment in HttpClientSettingsTest because the describe class does not exist anymore.
> Fixed #1213 - powermock-api-mockito2 seemed to be superfluous

- .github/workflows/maven-central.yml
Disable tests & docker operations for maven publish.
Part of https://github.com/artipie/artipie/issues/1206
> Disable tests & docker operations for maven publish

- .github/workflows/release.yml
- .wiki/Home.md
Don't release .jar to GitHub, since we release it to maven central now.
Part of #1206
> Don't release .jar to GitHub, since we release it to maven central now.

- src/main/java/com/artipie/api/AuthTokenRest.java
- src/main/java/com/artipie/api/RestApi.java
- src/main/java/com/artipie/auth/JwtTokenAuth.java
- src/test/java/com/artipie/auth/JwtTokenAuthTest.java
Part of #1227 
Added implementation of `TokenAuthentication` from our `http` to authenticate user by JWT token issued by our rest api. This implementation will be used in npm-adapter later. 
Also, 
- added user groups to the token as they are part of authorization process 
- corrected `com.artipie.api.RestApi#addJwtAuth` method and its usage to use auth in all rest api methods
> feat: validate JWT tokens

- .wiki/_Sidebar.md
> Add link for Keycloak credentials in wiki sidebar.

- src/main/java/com/artipie/settings/ConfigFile.java
- src/test/java/com/artipie/settings/ConfigFileTest.java
closes #1241 
Fixed `ConfigFile` to check extension of hidden files properly. On start Artipie scans configs directory looking for repository configs and tries to create repositories from `.yml` and `.yaml` files. If yaml file content is invalid, it writes an exception into log and continue the work. 
Note, that in the case, when hidden file is valid repository config, the repository will be started and will have path with dot, for example: `artipie/.my-hidden-bin-repo`.
Basically, we do not expect users to have any other files except for repository and artipie configs in the configuration storage.
> fix: ignore not proper files from repo config storage

- src/main/java/com/artipie/auth/AuthFromStorage.java
- src/test/java/com/artipie/auth/AuthFromStorageTest.java
part of #1237 
Added `Authentication` implementation to check user password from storage. It will be used with new policy/permissions implementation.
Also, I think it would be better to correct `Authentication` and `Policy` interfaces to return `CompletionStage`. Now implementations use `BlockingStorage` and thus blocking operations occurs in the chain of non-blocking requests. What do you say?
> feat: auth from storage

- pom.xml
Removed redundant line in `pom.xml`
Parameter `maven.compiler.target` doesn't exist in the maven javadoc plugin.
> Removed redundant line in pom.xml

- src/main/java/com/artipie/settings/SettingsFromPath.java
- src/main/resources/example/repo/artipie/my-docker.yaml
- src/main/resources/example/repo/artipie/my-maven.yaml
- src/main/resources/example/security/roles/reader.yml
part of #1237 
corrected copying of default settings:
1) storage aliases file is located inside repo dir now
2) permissions sections removed from repo settings
3) added read permissions for any repo
> fix: correct default settings copy

- pom.xml
- src/main/java/com/artipie/api/perms/ApiAliasPermission.java
- src/main/java/com/artipie/api/perms/ApiRepositoryPermission.java
- src/main/java/com/artipie/api/perms/ApiRolePermission.java
- src/main/java/com/artipie/api/perms/ApiUserPermission.java
- src/main/java/com/artipie/api/perms/RestApiPermission.java
- src/test/java/com/artipie/api/RestApiPermissionsTest.java
- src/test/java/com/artipie/api/perms/RestApiPermissionCollectionTest.java
Part of #1273 
Added test for rest api with permissions and corrected rest api permission collection. As we use heterogeneous collection `java.security.Permissions` each permission class must have his own collection class. 
Also initial collection implementation was not correct because permission key contained action mask. Mask can differ depending on allowed actions list (it can be `create and delete` or `update and enable` or etc), thus checking for action `create` we will never get suitable permission from collection map by key.
> feat: test for rest api permissions

- .wiki/Configuration-Policy.md
- pom.xml
- src/main/java/com/artipie/settings/SettingsFromPath.java
- src/main/resources/example/security/roles/api-admin.yaml
- src/main/resources/example/security/users/artipie.yaml
- src/main/resources/swagger-ui/swagger-initializer-flat.js
- src/main/resources/swagger-ui/swagger-initializer-org.js
- src/test/java/com/artipie/api/AuthRestOrgTest.java
- src/test/java/com/artipie/api/RepositoryRestOrgTest.java
- src/test/java/com/artipie/api/RestApiPermissionsTest.java
- src/test/java/com/artipie/api/RolesRestTest.java
- src/test/resources/security/roles/admin.yaml
closes #1237
added docs, updated http and `all_permission` name, added role for example settings
> feat: docs for REST API permissions

- src/main/java/com/artipie/SliceFromConfig.java
Composer repository was free of permission check. I try to fix it.
There was a simple class constructor used, which set unrestricted access to repo.
I'm not a java developer, so made by analogy with other policy's changes.
And FYI same situation might be with gem repo.
Part of #1237
> feat: composer instance to use permissions policy

- examples/artipie.yml
- pom.xml
- src/main/java/com/artipie/SliceFromConfig.java
- src/main/java/com/artipie/VertxMain.java
- src/main/java/com/artipie/db/ArtifactDbFactory.java
- src/main/java/com/artipie/db/DbConsumer.java
- src/main/java/com/artipie/http/ArtipieRepositories.java
- src/main/java/com/artipie/http/MainSlice.java
- src/main/java/com/artipie/http/SliceByPath.java
- src/main/java/com/artipie/settings/Settings.java
- src/main/java/com/artipie/settings/SettingsFromPath.java
- src/main/java/com/artipie/settings/YamlSettings.java
- src/test/java/com/artipie/SchedulerDbTest.java
- src/test/java/com/artipie/api/SSLJksRestTest.java
- src/test/java/com/artipie/api/SSLPemRestTest.java
- src/test/java/com/artipie/api/SSLPfxRestTest.java
- src/test/java/com/artipie/auth/AuthFromKeycloakTest.java
- src/test/java/com/artipie/db/DbConsumerTest.java
- src/test/java/com/artipie/http/DockerRoutingSliceTest.java
- src/test/java/com/artipie/settings/YamlSettingsTest.java
- src/test/java/com/artipie/settings/cache/CachedStoragesTest.java
- src/test/java/com/artipie/test/TestSettings.java
- src/test/resources/artipie-repo-config-key.yaml
- src/test/resources/artipie.yaml
- src/test/resources/artipie_with_policy.yaml
part of #1291 
Added consumer to insert and remove records from database, provided queue to adapters and added initiation of scheduler.
Also added tests. 
Note, that consumer accepts connection, not data source. Such approach is good for [sqlite db](https://stackoverflow.com/questions/15822778/sqlite-connection-pool-in-java-locked-database), but will not be suitable for connection pool and normal db (as postgresql or mysql).
> feat: added consumer and tests

- .github/workflows/perftest-client.yml
- .github/workflows/perftest-server.yml
Here's implementation of performance testing for Artipie. Part of  https://github.com/artipie/benchmarks/issues/64
It runs with self-hosted GitHub runners. Currently tests run for localhost and by ethernet between two machines. Localhost results are more stable, due to escaping all extra routing and security software checks.
This workflows do tests and generate two sets of graphs: for git tags: `v*` and `t*` (release tags and test tags)
> performance tests implementation

- .github/workflows/perftest-client.yml
- .github/workflows/perftest-server.yml
Restored lost 'then' (when removed TODOs) + spelling. Part of  https://github.com/artipie/benchmarks/issues/64
> Restored lost 'then' + spelling

- examples/maven/run.sh
- examples/run.sh
Fixing smoke test fails. This should fix smoke test fails + provide more logs in the future. I think Artipie server sometimes initializing longer than expected in the tests.
> Fixing smoke test fails

- .github/workflows/maven-adapter-release.yml
- README.md
- artipie-core/src/main/java/com/artipie/security/perms/UserPermissions.java
- artipie-main/pom.xml
- artipie-main/src/main/resources/example/artipie.yaml
- composer-adapter/pom.xml
- conan-adapter/pom.xml
- conda-adapter/pom.xml
- debian-adapter/pom.xml
- files-adapter/src/test/java/com/artipie/files/FileProxySliceITCase.java
- gem-adapter/pom.xml
- helm-adapter/pom.xml
- hexpm-adapter/pom.xml
- maven-adapter/pom.xml
- npm-adapter/pom.xml
- nuget-adapter/pom.xml
- pom.xml
- rpm-adapter/pom.xml
Corrected approach with different java versions for different modules: 
- it's more correct to use [`--release`](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-release.html) javac option instead of `target` and `source` and there is no need to compile with lower java version, [java will do all the magic itself](https://www.baeldung.com/java-compiler-release-option) 
- used `maven-compiler-plugin` to set different release version for tests. Thus, our test code does not have to be compatible with java 8, we can use new classes and features. 
- If any not java8 compatible feature was used in the main code, compilation will fail
- artipie-main, hex and maven adapters can use java 21 in the main code (these modules are not used by Chinees team)
> fix: use --release option

- .github/workflows/docker-ubuntu-release.yml
- artipie-main/Dockerfile-ubuntu
- artipie-main/pom.xml
- maven-adapter/src/main/java/com/artipie/maven/http/CachedProxySlice.java
- pom.xml
part of https://github.com/artipie/maven-resolver-http3-plugin/issues/12 
- As http3 does not work on standard jdk image, I've added configuration to release artipie based on ubuntu docker image
- Fixed maven adapter to send to client headers received from proxy server  
- Removed log4j which were moved to reload4j
> feat: artipie-ubuntu docker release

- conda-adapter/src/main/java/com/artipie/conda/asto/AstoMergedJson.java
- conda-adapter/src/main/java/com/artipie/conda/http/UpdateSlice.java
- conda-adapter/src/test/java/com/artipie/conda/http/UpdateSliceTest.java
This is hotfix for conda+s3 bug.  There are two interrelated issues (parts) in this bug:
1. Hangs in reads from asto ContentAsInputStream.inputStream().
Instances of PublisherAs(content) can read data from content correctly, so modified implementation is introduced, which uses `byte[]` instead of `InputStream`. Also, anaconda may hang up after some time after hang, but may not print any error messages. This is hot-fix, so deeper bug investigation will be performed after it. 
2. In case of the file stuck in `.uploads/` directory (broken connection, artipie freeze, reboos, client quits, etc.), adapter just returns BAD_REQUEST without any extra log messages or `.uploads/` cleanup. Moreover, anaconda doesn't print any error messages. As for now, I use `Storage.exclusively()` for synchronizing …
> Trying to hot-fix s3 bug. Hangs in reads from asto

- helm-adapter/src/main/java/com/artipie/helm/AddWriter.java
- helm-adapter/src/main/java/com/artipie/helm/RemoveWriter.java
- helm-adapter/src/test/java/com/artipie/helm/HelmAstoAddTest.java
- helm-adapter/src/test/java/com/artipie/helm/HelmAstoReindexTest.java
While working on https://github.com/artipie/artipie/issues/1343 I had intermittent helm adapter tests fails. So I investigated it and prepared helm adapter tests fix. The problem was that java `java.io.BufferedWriter` doesn't propagate `close()` call downstream, it just flushes its own data and resets its reference. So, closing streams properly allowed also to enable few other disabled helm tests without intermittent test fails, as yet.
Interestingly, in [JDK7](https://github.com/openjdk/jdk/blob/jdk7-b147/jdk/src/share/classes/java/io/BufferedWriter.java#L258) it would close its stream, but in [JDK8](https://github.com/openjdk/jdk/blob/jdk8-b120/jdk/src/share/classes/java/io/BufferedWriter.java#L259) it didn't. [JDK21](https://github.com/openjdk/jdk/blob/jdk-21%2B35/src/java.base/share/cl …
> Helm tests fix

- docker-adapter/src/main/java/com/artipie/docker/cache/CacheManifests.java
docker-adapter: fixed async copy without proper waiting. Could also fix intermittent test fail. Usually happens in "CI checks / maven-build (windows-latest) ".
```
........
Error:  Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.179 s <<< FAILURE! -- in com.artipie.docker.cache.CacheManifestsTest
Error:  com.artipie.docker.cache.CacheManifestsTest.shouldCacheManifest -- Time elapsed: 0.132 s <<< FAILURE!
java.lang.AssertionError: Artifact metadata were added to queue
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:26)
at com.artipie.docker.cache.CacheManifestsTest.shouldCacheManifest(CacheManifestsTest.java:108)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at …
```
> docker-adapter: fixed async copy without waiting

- artipie-main/examples/run.sh
- asto/asto-core/src/main/java/com/artipie/asto/streams/StorageValuePipeline.java
- asto/asto-core/src/main/java/com/artipie/asto/test/ReadWithDelaysStorage.java
- asto/asto-core/src/test/java/com/artipie/asto/streams/StorageValuePipelineTest.java
- asto/asto-s3/src/test/java/com/artipie/asto/StorageValuePipelineS3Test.java
- conda-adapter/src/main/java/com/artipie/conda/asto/AstoMergedJson.java
Fixing deadlock in `StorageValuePipeline.java` + test in asto-s3. Hotfix is removed.
Deadlock happens when Publisher for the `InputStream` produces data in the same thread as `action` callback by several chunks, and `action` callback actually does blocking `read()` on provided `InputStream`. Since plain `read()` is blocking, event loop doesn't get called, Publisher doesn't provide next part of the data and `read()` gets stuck. This situation always happens for S3Storage, since AWS S3 SDK invokes callback in one of its AWS threads and provides Publisher from that same thread too. The solution was to call `action` with the blocking `read()` in async block, from different thread.
Also, I had problems with `PublishingOutputStream` being stuck or incorretly callbacked, if `onComplete()` wasn't …
> Conda + s3 bug fix

- composer-adapter/src/main/java/com/artipie/composer/AstoRepository.java
- composer-adapter/src/main/java/com/artipie/composer/JsonPackage.java
- composer-adapter/src/test/java/com/artipie/composer/AstoRepositoryAddJsonTest.java
- composer-adapter/src/test/java/com/artipie/composer/JsonPackageTest.java
- composer-adapter/src/test/java/com/artipie/composer/JsonPackagesTest.java
composer adapter optimization/possible intermittent test fail fix. Found out that json data gets parsed to JsonObject multiple times, on every getter-like function, so I switched to parsing it only once in the constructor. Also may fix intermittent test fails like below.
```
.............
Caused by: javax.json.stream.JsonParsingException: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN, STRING, NUMBER, TRUE, FALSE, NULL]
at org.glassfish.json.JsonParserImpl.parsingException(JsonParserImpl.java:450)
at org.glassfish.json.JsonParserImpl.access$1100(JsonParserImpl.java:79)
at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:438)
at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:376)
at …
```
> composer optimization/intermittent test fail fix

- asto/asto-core/src/main/java/com/artipie/asto/fs/FileStorage.java
Fix for intermittent test fails due to empty dirs simultanious removal. Windows/Linux.
It happens when we use `FileStorage` and we remove common empty subdirectories (`deleteEmptyParts()`) simultaneously for 2+ keys, as part of `key` removal operation. Since those common empty subdirectories doesn't have any extra functionality/meaning, their non-existence should be ignored on removal.
Example of intermittent fail:
```
......
Caused by: com.artipie.asto.ArtipieIOException: java.nio.file.NoSuchFileException: /tmp/junit7472437463326177656/repo/bundle100/0f93eb03-2f5d-42a1-afd0-b2d7dd6df314
at com.artipie.asto.fs.FileStorage.deleteEmptyParts(FileStorage.java:269)
at com.artipie.asto.fs.FileStorage.lambda$delete$12(FileStorage.java:179)
at …
```
> Fix for intermittent test fails.

- artipie-main/src/main/java/com/artipie/settings/RepoData.java
Intermittent test fail fix: RepoDataTest.removesData » Completion java.io.UncheckedIOException: java.nio.file.NoSuchFileException
CompletableFuture was just returned by `thenAccept()`, must be awaited by `thenCompose()`.
Fail example is below.
```
Error:  com.artipie.settings.RepoDataTest.removesData -- Time elapsed: 0.008 s <<< ERROR!
java.util.concurrent.CompletionException: java.io.UncheckedIOException: java.nio.file.NoSuchFileException: /tmp/junit8233760876496059153/my-repo/first.txt
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
at …
```
> Intermittent test fail fix: RepoDataTest.removesData

- http-client/src/test/java/com/artipie/http/client/jetty/JettyClientSlicesTest.java
JettyClientSlicesTest intermittent test fail due to test sites glitches. See https://github.com/artipie/artipie/issues/1413
> JettyClientSlicesTest intermittent test fail

- asto/asto-core/src/main/java/com/artipie/asto/test/StorageWhiteboxVerification.java
Intermittent test fails fix in FileStorageWhiteboxVerificationTest.
We should wait for unfinished file operations on temporary files before test ends, or we are getting into race condition with junit.
Log example:
```
Error:  com.artipie.asto.FileStorageWhiteboxVerificationTest.exclusively_shouldFailExclusivelyForSameKey -- Time elapsed: 0.091 s <<< ERROR!
java.io.IOException: Failed to delete temp directory C:\Users\RUNNER~1\AppData\Local\Temp\junit11463551415899198878. The following paths could not be deleted (see suppressed exceptions for details): sub-storage\test-prefix
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.ja …
```
> Intermittent test fails fix in FileStorageWhiteboxVerificationTest

- maven-adapter/src/main/java/com/artipie/maven/http/CachedProxySlice.java
Intermittent test fail fix. Event added after completion of the promise.
Log example:
```
Error:  Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.468 s <<< FAILURE! -- in com.artipie.maven.http.MavenProxySliceITCase
Error:  com.artipie.maven.http.MavenProxySliceITCase.downloadsJarFromCentralAndCachesIt -- Time elapsed: 0.049 s <<< FAILURE!
java.lang.AssertionError: Event was added to queue
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:26)
at com.artipie.maven.http.MavenProxySliceITCase.downloadsJarFromCentralAndCachesIt(MavenProxySliceITCase.java:112)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
[INFO] 
[INFO] Results: …
```
> Intermittent test fail fix

- artipie-main/pom.xml
Maintainer info is required for publishing
```
Rule failure while trying to close staging repository with ID "comartipie-1753".
Error:  
Error:  Nexus Staging Rules Failure Report
Error:  ==================================
Error:  
Error:  Repository "comartipie-1753" failures
Error:    Rule "pom-staging" failures
Error:      * Invalid POM: /com/artipie/artipie/v1.17.11/artipie-v1.17.11.pom: Developer information missing
Error:  
Error:  
```
> Maintainer info is required for publishing

- artipie-main/pom.xml
- pom.xml
Developer information must be in root pom.xml for publishing artifacts.
> Developer information must be in root pom.xml for publishing artifacts.

- artipie-main/pom.xml
config for the maven-compiler-plugin adjusted (21->17)
> fix for branch "jdk17-build" broken 

- artipie-main/pom.xml
- pom.xml
> fix for missing dependencies httpcore5/httpcore5-h2 (#1447)
